"""Regenerate the Unicode tables embedded in web/checker.js from this Python's unicodedata.

The phone checker must read text exactly as the node's Python does. Two things cannot be taken from
the browser's own Unicode support, because a browser may ship a newer Unicode version than the
node's Python (3.11 knows Unicode 14.0; Chrome and Safari in 2026 know 15-17):

  UNASSIGNED  code points Python thinks are unassigned. The checker swaps them for private-use
              stand-ins while it works, so a letter or digit added in a later Unicode version stays an
              unknown symbol (not a letter, not a digit, no case, no decomposition), as on the node.
  FOLD        characters whose str.casefold() differs from str.lower() (which equals JS
              toLowerCase() for every Unicode 14 character); only those that can survive NFKC.
  ZEROS       the DIGIT ZERO of every Unicode 14 decimal-digit run, so float() and the
              digit-reading in amounts accept the same digits Python does.

  python tests/js/gen_unicode_tables.py          rewrite the block in web/checker.js
  python tests/js/gen_unicode_tables.py --check  exit 1 if the block is out of date
"""
from __future__ import annotations

import sys
import unicodedata as ud
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CHECKER = ROOT / "web" / "checker.js"
BEGIN, END = "// <unicode-tables generated by tests/js/gen_unicode_tables.py>", "// </unicode-tables>"
MAX = sys.maxunicode + 1


def b36(n: int) -> str:
    digits = "0123456789abcdefghijklmnopqrstuvwxyz"
    out = ""
    while True:
        n, r = divmod(n, 36)
        out = digits[r] + out
        if not n:
            return out


def unassigned_ranges() -> str:
    ranges: list[list[int]] = []
    for c in range(MAX):
        if 0xD800 <= c <= 0xDFFF or ud.category(chr(c)) != "Cn":
            continue
        if ranges and ranges[-1][1] == c - 1:
            ranges[-1][1] = c
        else:
            ranges.append([c, c])
    # delta-coded: "<gap from previous end + 1>.<length - 1>" in base 36
    prev, toks = -1, []
    for a, b in ranges:
        toks.append(f"{b36(a - prev - 1)}.{b36(b - a)}")
        prev = b
    return " ".join(toks)


def fold_table() -> str:
    entries = []
    for c in range(MAX):
        ch = chr(c)
        if 0xD800 <= c <= 0xDFFF or ud.category(ch) == "Cn":
            continue
        if ch.casefold() != ch.lower() and ud.normalize("NFKC", ch) == ch:
            entries.append((c, ch.casefold()))
    # runs of single-character mappings that advance together: [first, count, first target]
    out, i = [], 0
    while i < len(entries):
        c, f = entries[i]
        if len(f) == 1:
            j = i
            while (j + 1 < len(entries) and len(entries[j + 1][1]) == 1 and entries[j + 1][0] == entries[j][0] + 1
                   and ord(entries[j + 1][1]) == ord(entries[j][1]) + 1):
                j += 1
            out.append(f"[0x{c:x},{j - i + 1},0x{ord(f):x}]")
            i = j + 1
        else:
            out.append(f"[0x{c:x},\"" + "".join(f"\\u{{{ord(x):x}}}" for x in f) + "\"]")
            i += 1
    return ",".join(out)


def zeros() -> str:
    zs = [c for c in range(MAX) if ud.category(chr(c)) == "Nd" and ud.decimal(chr(c)) == 0]
    for z in zs:  # every run is exactly ten digits, zero first
        assert all(ud.decimal(chr(z + k), -1) == k for k in range(10)), hex(z)
    return ",".join(f"0x{z:x}" for z in zs)


def block() -> str:
    return "\n".join([
        BEGIN,
        f"  // Python {sys.version_info.major}.{sys.version_info.minor}, unicodedata {ud.unidata_version}",
        f"  const UNICODE_VERSION = \"{ud.unidata_version}\";",
        f"  const UNASSIGNED = \"{unassigned_ranges()}\";",
        f"  const FOLD = [{fold_table()}];",
        f"  const ZEROS = [{zeros()}];",
        "  " + END,
    ])


def main() -> int:
    src = CHECKER.read_text(encoding="utf-8")
    a, b = src.index(BEGIN), src.index(END) + len(END)
    new = src[:a] + block().rstrip() + src[b:]
    if "--check" in sys.argv:
        if new != src:
            print("web/checker.js: Unicode tables are out of date; run python tests/js/gen_unicode_tables.py")
            return 1
        print("web/checker.js: Unicode tables up to date (unicodedata %s)" % ud.unidata_version)
        return 0
    CHECKER.write_text(new, encoding="utf-8")
    print("web/checker.js: wrote Unicode tables (unicodedata %s)" % ud.unidata_version)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
