"""Pack update prepared on 7 Oct 2026 (fraud pack 1.6.0), from a blind red team and real published messages.
Run it once on a machine with a signer's key (SAHAYAK_SIGNER; see scripts/sign_packs.py): it edits the pack and re-signs it.
Safe to run twice: each change is applied only once. The engine code that uses these entries is in
sahayak/fraud/signals.py and web/checker.js; each rule stays off until this pack defines its entries.

  SAHAYAK_SIGNER=roshan python scripts/pack_update_1_6.py
  python -m pytest

What it adds, and why (every change was measured on all benchmark sets before it was adopted; PROGRESS.md D37):
- no_pressure (-0.5): a message that says there is no hurry ("koi jaldi nahi", "jab time mile") is not rushing you;
  it also stops "urgency" firing. Family money requests were flagged for a date in them.
- wrong_transfer (+2.5) and the category wrong_credit: "money reached you by mistake, send it back" (the fake
  "credited" SMS, then a request to return it).
- donation_appeal (+1.5) and the category charity: a donation asked to a personal UPI ID or phone number.
- investment: gold trading, crypto, forex and bitcoin in Hindi and English.
- job_fee (+3.0): a job offer that asks you to pay first (training kit, verification, uniform).
- in_person (-2.0): an invitation to come to a camp, office, shop or interview, or to bring your papers, with no
  money, code, unknown link or UPI ID asked. Scammers work remotely.
- nothing_asked (-1.5): a described call where the caller asked for nothing.
- doorstep_code (-1.5) with the handover lexicons: the delivery code you give at the door once the parcel or
  cylinder is in your hands; on a call, a caller asking for the code is still the scam.
- maintenance_terms: a power cut explained as maintenance work is a notice, not the unpaid-bill threat.
- otp_terms += "dac", "delivery authentication code"; share_verbs += "read it to him/her", "asked me to read";
  advisory += "saavdhan" and its spellings.
From the DEV half of PublicBench (real published messages; the test half stays unread), narrow wordings only:
- threat_terms: a fake police or court notice ("a report has been filed against you", "court order against your
  IP", "pornographic", "गंदी फिल्म"); advance_fee: a fee to release a payment ("tax for releasing the payment",
  "security fee", "सिक्योरिटी फीस"), never a plain "pay the tax" (real Income Tax messages say that);
  prize: "prize amount", "letter of guarantee", "केबीसी", "भाग्यशाली ड्रा".
- emergency_terms and money_send_terms: "your son has been caught/arrested ... please pay him".
- sextortion: Hindi blackmail words ("ब्लैकमेल", "धमकी"), photos ("तस्वीरें") and "सोशल मीडिया पर प्रसारित".
- code_phrases: "I accidentally sent you a message, forward it" (the WhatsApp account-takeover code);
  share_verbs: "dial the" (a call asking you to key in the code you received).
- investment: stock-group openers ("learning community", "want to invest in the stock market").
Hindi strings, like the rest of the pack, still need a native speaker's review.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from scripts.packtool import load, save  # noqa: E402

NEW_LEXICONS = {'no_pressure': ['no hurry',
                                'no rush',
                                'no urgency',
                                'not urgent',
                                'nothing urgent',
                                'no need to hurry',
                                'no need to rush',
                                "don't hurry",
                                'dont hurry',
                                "don't rush",
                                'dont rush',
                                'take your time',
                                'whenever you can',
                                'whenever you get time',
                                'whenever you are free',
                                "whenever you're free",
                                'when you get time',
                                'when you get a chance',
                                'when you have time',
                                'when you are free',
                                "when you're free",
                                'in your free time',
                                'koi jaldi nahi',
                                'koi jaldi nahin',
                                'jaldi nahi hai',
                                'jaldi nahin hai',
                                'jaldi ki koi baat nahi',
                                'koi jaldbazi nahi',
                                'koi hurry nahi',
                                'jab time mile',
                                'jab time mil jaye',
                                'jab time ho',
                                'jab time milega',
                                'jab fursat ho',
                                'jab fursat mile',
                                'jab free ho',
                                'jab free ho jao',
                                'कोई जल्दी नहीं',
                                'जल्दी नहीं है',
                                'जल्दी की कोई बात नहीं',
                                'कोई जल्दबाजी नहीं',
                                'जब टाइम मिले',
                                'जब टाइम हो',
                                'जब टाइम मिल जाए',
                                'जब समय मिले',
                                'जब समय हो',
                                'जब फुर्सत हो',
                                'जब फुर्सत मिले',
                                'जब फ्री हो'],
                'mistake_terms': ['by mistake',
                                  'mistakenly',
                                  'accidentally',
                                  'accidently',
                                  'wrongly sent',
                                  'wrongly transferred',
                                  'wrongly credited',
                                  'sent wrongly',
                                  'transferred wrongly',
                                  'sent in error',
                                  'transferred in error',
                                  'credited in error',
                                  'wrong number',
                                  'wrong account',
                                  'wrong upi',
                                  'galti se',
                                  'galati se',
                                  'galti me',
                                  'galti mein',
                                  'galat number',
                                  'galat account',
                                  'galat khate',
                                  'galat upi',
                                  'bhool se',
                                  'bhul se',
                                  'गलती से',
                                  'गलती में',
                                  'भूल से',
                                  'भूलवश',
                                  'गलत नंबर',
                                  'गलत खाते',
                                  'गलत खाता',
                                  'गलत अकाउंट',
                                  'गलत यूपीआई'],
                'return_request': ['return it',
                                   'return it back',
                                   'return the money',
                                   'return the amount',
                                   'return the extra',
                                   'return the excess',
                                   'return the balance',
                                   'return the remaining',
                                   'return the rest',
                                   'return my money',
                                   'please return',
                                   'kindly return',
                                   'pls return',
                                   'plz return',
                                   'send it back',
                                   'send back',
                                   'send the money back',
                                   'send the amount back',
                                   'send the extra back',
                                   'send my money back',
                                   'transfer it back',
                                   'transfer back',
                                   'transfer the money back',
                                   'wapas kar do',
                                   'wapas kardo',
                                   'wapas karo',
                                   'wapas kar dijiye',
                                   'wapas kar dena',
                                   'wapas kar dein',
                                   'wapas kar de',
                                   'wapas bhej do',
                                   'wapas bhejo',
                                   'wapas bhej dijiye',
                                   'wapas bhej dena',
                                   'wapas bhej dein',
                                   'wapas bhej de',
                                   'wapas daal do',
                                   'wapas transfer kar do',
                                   'vapas kar do',
                                   'vapas karo',
                                   'vapas kar dijiye',
                                   'vapas kar dena',
                                   'vapas bhej do',
                                   'vapas bhejo',
                                   'vapas bhej dijiye',
                                   'vapas bhej dena',
                                   'wapis kar do',
                                   'wapis bhej do',
                                   'lauta do',
                                   'lauta dijiye',
                                   'lauta dena',
                                   'return kar do',
                                   'return kardo',
                                   'return karo',
                                   'return kar dijiye',
                                   'return kar dena',
                                   'return kar dein',
                                   'वापस कर दो',
                                   'वापस कर दें',
                                   'वापस कर दीजिए',
                                   'वापस कर दीजिये',
                                   'वापस करो',
                                   'वापस करें',
                                   'वापस कर देना',
                                   'वापस भेज दो',
                                   'वापस भेज दें',
                                   'वापस भेज दीजिए',
                                   'वापस भेजो',
                                   'वापस भेजें',
                                   'वापस भेज देना',
                                   'वापस डाल दो',
                                   'वापिस कर दो',
                                   'वापिस भेज दो',
                                   'लौटा दो',
                                   'लौटा दें',
                                   'लौटा दीजिए',
                                   'लौटा देना',
                                   'लौटाओ',
                                   'लौटाएं',
                                   'रिटर्न कर दो',
                                   'रिटर्न कर दें'],
                'donation_terms': ['donate',
                                   'donation',
                                   'donations',
                                   'contribute',
                                   'fundraiser',
                                   'fund raiser',
                                   'crowdfunding',
                                   'crowd funding',
                                   'daan',
                                   'yogdan',
                                   'sahyog rashi',
                                   'sahayata rashi',
                                   'दान',
                                   'योगदान',
                                   'सहयोग राशि',
                                   'सहायता राशि',
                                   'आर्थिक सहायता',
                                   'आर्थिक मदद'],
                'job_terms': ['job',
                              'jobs',
                              'naukri',
                              'naukari',
                              'नौकरी',
                              'interview',
                              'interviews',
                              'इंटरव्यू',
                              'recruitment',
                              'recruiter',
                              'recruiting',
                              'hiring',
                              'vacancy',
                              'vacancies',
                              'वैकेंसी',
                              'offer letter',
                              'appointment letter',
                              'joining letter',
                              'direct joining',
                              'joining kit',
                              'joining date',
                              'date of joining',
                              'joining se pehle',
                              'confirm your joining',
                              'confirm joining',
                              'placement agency',
                              'placement consultancy',
                              'ctc',
                              'employment',
                              'rozgar',
                              'रोजगार',
                              'shortlisted',
                              'selected for',
                              'you are selected',
                              'you have been selected',
                              "you've been selected",
                              'i have been selected',
                              "i've been selected",
                              'i was selected',
                              'aapka selection',
                              'selection ho gaya',
                              'selection hua',
                              'post ke liye',
                              'for the post',
                              'आपका चयन',
                              'चयन हो गया',
                              'चयन हुआ',
                              'पद'],
                'bring_verbs': ['bring',
                                'carry',
                                'saath laana',
                                'saath lana',
                                'saath laani',
                                'saath lani',
                                'saath laane',
                                'saath lane',
                                'saath laao',
                                'saath lao',
                                'saath laayein',
                                'saath layein',
                                'saath laaiye',
                                'saath laiye',
                                'sath laana',
                                'sath lana',
                                'sath laani',
                                'sath laane',
                                'sath lane',
                                'sath lao',
                                'laana hai',
                                'lana hai',
                                'laani hai',
                                'lani hai',
                                'laane hain',
                                'lane hain',
                                'laana hoga',
                                'lana hoga',
                                'laani hogi',
                                'lani hogi',
                                'laane honge',
                                'lane honge',
                                'le aana',
                                'le aao',
                                'le aaiye',
                                'le aayein',
                                'lekar aana',
                                'lekar aao',
                                'lekar aaiye',
                                'lekar aayein',
                                'le kar aana',
                                'leke aana',
                                'leke aao',
                                'leke aaiye',
                                'le ke aana',
                                'saath le aana',
                                'saath lekar aana',
                                'saath lekar aayein',
                                'साथ लाएं',
                                'साथ लायें',
                                'साथ लाना',
                                'साथ लानी',
                                'साथ लाने',
                                'साथ लाइए',
                                'साथ लाओ',
                                'लाना है',
                                'लानी है',
                                'लाने हैं',
                                'लाना होगा',
                                'लानी होगी',
                                'लाने होंगे',
                                'लेकर आएं',
                                'लेकर आना',
                                'लेकर आइए',
                                'लेकर आओ',
                                'ले आएं',
                                'ले आना',
                                'ले आइए',
                                'साथ लेकर आएं',
                                'साथ ले आएं'],
                'bring_items': ['resume',
                                'cv',
                                'biodata',
                                'bio-data',
                                'certificate',
                                'certificates',
                                'document',
                                'documents',
                                'original',
                                'originals',
                                'photo',
                                'photos',
                                'photograph',
                                'photographs',
                                'copy',
                                'copies',
                                'xerox',
                                'photocopy',
                                'photocopies',
                                'id proof',
                                'aadhaar',
                                'aadhar',
                                'pan card',
                                'ration card',
                                'passbook',
                                'passbooks',
                                'marksheet',
                                'marksheets',
                                'mark sheet',
                                'admit card',
                                'call letter',
                                'offer letter',
                                'आधार',
                                'राशन कार्ड',
                                'दस्तावेज',
                                'प्रमाण पत्र',
                                'प्रमाणपत्र',
                                'फोटो',
                                'पासबुक',
                                'मार्कशीट',
                                'कागज',
                                'कागजात',
                                'ओरिजिनल',
                                'रिज्यूमे',
                                'बायोडाटा',
                                'पहचान पत्र'],
                'handover_done': ['handed me',
                                  'handed it to me',
                                  'handed it over',
                                  'handed over the parcel',
                                  'handed over the package',
                                  'handed over the cylinder',
                                  'handed over the order',
                                  'handed over the product',
                                  'handed over the item',
                                  'handed over the food',
                                  'handed over my parcel',
                                  'handed over my package',
                                  'handed over my cylinder',
                                  'handed over my order',
                                  'handed over my product',
                                  'handed over my item',
                                  'handed over my food',
                                  'gave me the parcel',
                                  'gave me the package',
                                  'gave me the cylinder',
                                  'gave me the order',
                                  'gave me the product',
                                  'gave me the item',
                                  'gave me the food',
                                  'gave me my parcel',
                                  'gave me my package',
                                  'gave me my cylinder',
                                  'gave me my order',
                                  'gave me my product',
                                  'gave me my item',
                                  'gave me my food',
                                  'parcel le liya',
                                  'cylinder le liya',
                                  'order le liya',
                                  'saman le liya',
                                  'samaan le liya',
                                  'package le liya',
                                  'ne parcel de diya',
                                  'ne cylinder de diya',
                                  'ne order de diya',
                                  'ne saman de diya',
                                  'ne samaan de diya',
                                  'ne package de diya',
                                  'usne parcel de diya',
                                  'usne cylinder de diya',
                                  'usne order de diya',
                                  'usne saman de diya',
                                  'usne samaan de diya',
                                  'usne package de diya',
                                  'unhone parcel de diya',
                                  'unhone cylinder de diya',
                                  'unhone order de diya',
                                  'unhone saman de diya',
                                  'unhone samaan de diya',
                                  'unhone package de diya',
                                  'पार्सल ले लिया',
                                  'सिलेंडर ले लिया',
                                  'सिलिंडर ले लिया',
                                  'सामान ले लिया',
                                  'ऑर्डर ले लिया',
                                  'ने पार्सल दे दिया',
                                  'ने सिलेंडर दे दिया',
                                  'ने सिलिंडर दे दिया',
                                  'ने सामान दे दिया',
                                  'ने ऑर्डर दे दिया',
                                  'उसने पार्सल दे दिया',
                                  'उसने सिलेंडर दे दिया',
                                  'उसने सिलिंडर दे दिया',
                                  'उसने सामान दे दिया',
                                  'उसने ऑर्डर दे दिया',
                                  'उन्होंने पार्सल दे दिया',
                                  'उन्होंने सिलेंडर दे दिया',
                                  'उन्होंने सिलिंडर दे दिया',
                                  'उन्होंने सामान दे दिया',
                                  'उन्होंने ऑर्डर दे दिया'],
                'handover_when': ['time of delivery',
                                  'in your hand',
                                  'in your hands',
                                  'you receive the parcel',
                                  'you receive the package',
                                  'you receive the cylinder',
                                  'you receive the order',
                                  'you receive the product',
                                  'you receive the item',
                                  'you receive the food',
                                  'you receive your parcel',
                                  'you receive your package',
                                  'you receive your cylinder',
                                  'you receive your order',
                                  'you receive your product',
                                  'you receive your item',
                                  'you receive your food',
                                  'when the parcel arrives',
                                  'when the parcel comes',
                                  'when the parcel is delivered',
                                  'when the package arrives',
                                  'when the package comes',
                                  'when the package is delivered',
                                  'when the cylinder arrives',
                                  'when the cylinder comes',
                                  'when the cylinder is delivered',
                                  'when the order arrives',
                                  'when the order comes',
                                  'when the order is delivered',
                                  'when the product arrives',
                                  'when the product comes',
                                  'when the product is delivered',
                                  'when the item arrives',
                                  'when the item comes',
                                  'when the item is delivered',
                                  'when the food arrives',
                                  'when the food comes',
                                  'when the food is delivered',
                                  'jab parcel mil',
                                  'jab parcel aa',
                                  'jab parcel aaye',
                                  'jab cylinder mil',
                                  'jab cylinder aa',
                                  'jab cylinder aaye',
                                  'jab order mil',
                                  'jab order aa',
                                  'jab order aaye',
                                  'jab saman mil',
                                  'jab saman aa',
                                  'jab saman aaye',
                                  'jab samaan mil',
                                  'jab samaan aa',
                                  'jab samaan aaye',
                                  'jab package mil',
                                  'jab package aa',
                                  'jab package aaye',
                                  'parcel mil jaye to',
                                  'parcel mil jaye tab',
                                  'cylinder mil jaye to',
                                  'cylinder mil jaye tab',
                                  'order mil jaye to',
                                  'order mil jaye tab',
                                  'saman mil jaye to',
                                  'saman mil jaye tab',
                                  'samaan mil jaye to',
                                  'samaan mil jaye tab',
                                  'package mil jaye to',
                                  'package mil jaye tab',
                                  'parcel milne ke baad',
                                  'parcel milne par',
                                  'cylinder milne ke baad',
                                  'cylinder milne par',
                                  'order milne ke baad',
                                  'order milne par',
                                  'saman milne ke baad',
                                  'saman milne par',
                                  'samaan milne ke baad',
                                  'samaan milne par',
                                  'package milne ke baad',
                                  'package milne par',
                                  'haath me ho',
                                  'haath mein ho',
                                  'hath me ho',
                                  'hath mein ho',
                                  'delivery ke time',
                                  'delivery ke samay',
                                  'delivery ke waqt',
                                  'delivery ke wakt',
                                  'जब पार्सल मिल',
                                  'जब पार्सल आ',
                                  'जब सिलेंडर मिल',
                                  'जब सिलेंडर आ',
                                  'जब सिलिंडर मिल',
                                  'जब सिलिंडर आ',
                                  'जब सामान मिल',
                                  'जब सामान आ',
                                  'जब ऑर्डर मिल',
                                  'जब ऑर्डर आ',
                                  'पार्सल मिल जाए तो',
                                  'पार्सल मिल जाए तब',
                                  'सिलेंडर मिल जाए तो',
                                  'सिलेंडर मिल जाए तब',
                                  'सिलिंडर मिल जाए तो',
                                  'सिलिंडर मिल जाए तब',
                                  'सामान मिल जाए तो',
                                  'सामान मिल जाए तब',
                                  'ऑर्डर मिल जाए तो',
                                  'ऑर्डर मिल जाए तब',
                                  'पार्सल मिलने के बाद',
                                  'पार्सल मिलने पर',
                                  'सिलेंडर मिलने के बाद',
                                  'सिलेंडर मिलने पर',
                                  'सिलिंडर मिलने के बाद',
                                  'सिलिंडर मिलने पर',
                                  'सामान मिलने के बाद',
                                  'सामान मिलने पर',
                                  'ऑर्डर मिलने के बाद',
                                  'ऑर्डर मिलने पर',
                                  'हाथ में हो',
                                  'डिलीवरी के समय',
                                  'डिलीवरी के वक्त',
                                  'डिलीवरी के टाइम'],
                'handover_to': ['to the delivery person',
                                'to the delivery man',
                                'to the delivery boy',
                                'to the delivery guy',
                                'to the delivery agent',
                                'to the delivery associate',
                                'to the delivery partner',
                                'to the delivery executive',
                                'with the delivery person',
                                'with the delivery man',
                                'with the delivery boy',
                                'with the delivery guy',
                                'with the delivery agent',
                                'with the delivery associate',
                                'with the delivery partner',
                                'with the delivery executive',
                                'tell the delivery person',
                                'tell the delivery man',
                                'tell the delivery boy',
                                'tell the delivery guy',
                                'tell the delivery agent',
                                'tell the delivery associate',
                                'tell the delivery partner',
                                'tell the delivery executive',
                                'give the delivery person',
                                'give the delivery man',
                                'give the delivery boy',
                                'give the delivery guy',
                                'give the delivery agent',
                                'give the delivery associate',
                                'give the delivery partner',
                                'give the delivery executive',
                                'delivery wale ko',
                                'delivery wala ko',
                                'delivery vale ko',
                                'delivery boy ko',
                                'delivery man ko',
                                'delivery bhaiya ko',
                                'delivery partner ko',
                                'delivery agent ko',
                                'hawker ko',
                                'डिलीवरी वाले को',
                                'डिलीवरी वाला को',
                                'डिलीवरी बॉय को',
                                'डिलीवरी मैन को',
                                'डिलीवरी भैया को',
                                'हॉकर को'],
                'not_in_person': ['over the phone',
                                  'over phone',
                                  'on the phone',
                                  'on phone',
                                  'on the call',
                                  'over the call',
                                  'on call',
                                  'over call',
                                  'during the call',
                                  'phone pe hi',
                                  'phone par hi',
                                  'call pe',
                                  'call par',
                                  'call per',
                                  'कॉल पर',
                                  'कॉल पे',
                                  'फोन पर ही',
                                  'फोन पे ही',
                                  'to my neighbour',
                                  'to the neighbour',
                                  'with my neighbour',
                                  'with the neighbour',
                                  'to my neighbor',
                                  'to the neighbor',
                                  'with my neighbor',
                                  'with the neighbor',
                                  'to the guard',
                                  'with the guard',
                                  'to the security',
                                  'with the security',
                                  'to the watchman',
                                  'with the watchman',
                                  'neighbour ko',
                                  'padosi ko',
                                  'guard ko',
                                  'security ko',
                                  'watchman ko',
                                  'guard ke paas',
                                  'padosi ke paas',
                                  'पडोसी को',
                                  'गार्ड को',
                                  'पडोसी के पास',
                                  'गार्ड के पास'],
                'in_person': ['camp',
                              'walk-in',
                              'walk in interview',
                              'venue',
                              'community hall',
                              'panchayat bhawan',
                              'panchayat bhavan',
                              'visit us',
                              'do visit',
                              'please visit us',
                              'visit our store',
                              'visit our shop',
                              'visit our showroom',
                              'visit our office',
                              'at our store',
                              'at our shop',
                              'at our showroom',
                              'come to the',
                              'come to our',
                              'bring your',
                              'bring along',
                              'please bring',
                              'bring original',
                              'bring the original',
                              'carry your',
                              'please carry',
                              'carry original',
                              'carry the original',
                              'shivir',
                              'padhaarein',
                              'padharein',
                              'padhaare',
                              'padhare',
                              'padharen',
                              'zaroor aayein',
                              'jaroor aayein',
                              'zarur aayein',
                              'office aa jaana',
                              'office aana',
                              'office me aana',
                              'saath laayein',
                              'saath layein',
                              'saath laaye',
                              'saath laye',
                              'saath laana',
                              'saath lana',
                              'saath le aana',
                              'saath lekar aayein',
                              'lekar aayein',
                              'lekar aaye',
                              'lekar aana',
                              'leke aana',
                              'leke aaye',
                              'laani hai',
                              'lani hai',
                              'laana hai',
                              'शिविर',
                              'कैंप',
                              'पंचायत भवन',
                              'सामुदायिक भवन',
                              'पधार',
                              'अवश्य आएं',
                              'जरूर आएं',
                              'साथ लाएं',
                              'साथ लायें',
                              'साथ लाये',
                              'साथ लाना',
                              'साथ में लाएं',
                              'साथ लेकर आएं',
                              'लेकर आएं',
                              'लेकर आयें',
                              'लेकर आना',
                              'लेकर आइए',
                              'लेकर आइये',
                              'लानी है',
                              'लाना है'],
                'nothing_asked': ['did not ask for anything',
                                  "didn't ask for anything",
                                  'did not ask anything',
                                  "didn't ask anything",
                                  'asked for nothing',
                                  'nothing was asked',
                                  'did not want anything',
                                  "didn't want anything",
                                  'kuch maanga nahi',
                                  'kuch manga nahi',
                                  'kuch maanga nahin',
                                  'kuch nahi maanga',
                                  'kuch nahi manga',
                                  'kuch nahin maanga',
                                  'kuchh nahi maanga',
                                  'kuchh maanga nahi',
                                  'kuch nahi maangi',
                                  'kuch nahi mangi',
                                  'kuch nahi maange',
                                  'kuch nahi poocha',
                                  'kuch nahi pucha',
                                  'कुछ नहीं मांगा',
                                  'कुछ मांगा नहीं',
                                  'कुछ नहीं मांगी',
                                  'कुछ मांगी नहीं',
                                  'कुछ नहीं मांगे',
                                  'कुछ नहीं पूछा'],
                'maintenance_terms': ['maintenance',
                                      'maintainance',
                                      'repair work',
                                      'line work',
                                      'transformer',
                                      'planned shutdown',
                                      'marammat',
                                      'line ka kaam',
                                      'मरम्मत',
                                      'रखरखाव',
                                      'मेंटेनेंस',
                                      'ट्रांसफार्मर',
                                      'ट्रांसफॉर्मर',
                                      'लाइन का काम']}

APPEND_LEXICONS = {'investment': ['gold trading', 'गोल्ड ट्रेडिंग', 'क्रिप्टो', 'फॉरेक्स', 'बिटकॉइन', 'bitcoin'],
                   'advisory': ['saavdhan', 'savdhan', 'saavdhaan', 'sawdhan', 'thagon se', 'thago se'],
                   'otp_terms': ['dac', 'delivery authentication code'],
                   'share_verbs': ['read it to him', 'read it to her', 'asked me to read']}

NEW_SIGNALS = {'no_pressure': {'weight': -0.5,
                               'hard': False,
                               'category': None,
                               'show': True,
                               'negative': True,
                               'reason': {'en': 'It says there is no hurry ("{phrase}") and nothing else in it looks like a scam. '
                                                'Scams almost always rush you.',
                                          'hi': 'इसमें कहा गया है कि कोई जल्दी नहीं ("{phrase}") और इसमें ठगी का कोई और संकेत नहीं '
                                                'है। ठग लगभग हमेशा जल्दबाज़ी कराते हैं।'}},
               'wrong_transfer': {'weight': 2.5,
                                  'hard': False,
                                  'category': 'wrong_credit',
                                  'show': True,
                                  'reason': {'en': 'It says money reached you by mistake and asks you to send it back. Scammers '
                                                   "send fake 'money credited' SMS for this.",
                                             'hi': 'इसमें कहा गया है कि गलती से आपके पास पैसे आ गए और उन्हें वापस भेजने को कहा गया '
                                                   "है। ठग इसके लिए नकली 'पैसे जमा' SMS भेजते हैं।"}},
               'donation_appeal': {'weight': 1.5,
                                   'hard': False,
                                   'category': 'charity',
                                   'show': True,
                                   'reason': {'en': 'It asks for a donation to a personal UPI ID or phone number. Fake medical and '
                                                    'relief appeals work this way; check with the hospital or a verified '
                                                    'fundraiser before you give.',
                                              'hi': 'इसमें किसी निजी UPI ID या फ़ोन नंबर पर दान माँगा गया है। इलाज और राहत की नकली '
                                                    'अपीलें ऐसे ही चलती हैं; देने से पहले अस्पताल या किसी जाँचे-परखे फंडरेज़र से '
                                                    'पुष्टि करें।'}},
               'job_fee': {'weight': 3.0,
                           'hard': False,
                           'category': 'job_task',
                           'show': True,
                           'reason': {'en': 'It offers a job but asks you to pay money first. Real employers never charge to hire, '
                                            'train, kit out or verify you.',
                                      'hi': 'इसमें नौकरी के बदले पहले पैसे जमा करने को कहा गया है। असली नौकरी देने वाले भर्ती, '
                                            'ट्रेनिंग, किट या वेरिफ़िकेशन के पैसे नहीं लेते।'}},
               'in_person': {'weight': -2.0,
                             'hard': False,
                             'category': None,
                             'show': True,
                             'negative': True,
                             'reason': {'en': 'It asks you to come in person, to a camp, office, shop or interview, or to bring '
                                              'your papers, and asks for no money, code or link.',
                                        'hi': 'इसमें किसी कैंप, दफ़्तर, दुकान या इंटरव्यू पर खुद आने, या अपने कागज़ात साथ लाने को '
                                              'कहा गया है, और कोई पैसा, कोड या लिंक नहीं माँगा गया।'}},
               'nothing_asked': {'weight': -1.5,
                                 'hard': False,
                                 'category': None,
                                 'show': True,
                                 'negative': True,
                                 'reason': {'en': 'You say the caller asked for no money, code or details.',
                                            'hi': 'आपके अनुसार फ़ोन करने वाले ने कोई पैसा, कोड या जानकारी नहीं माँगी।'}},
               'doorstep_code': {'weight': -1.5,
                                 'hard': False,
                                 'category': None,
                                 'show': True,
                                 'negative': True,
                                 'reason': {'en': 'The code goes to the delivery person at your door once the parcel or cylinder '
                                                  'is in your hands. That is how delivery codes work. Never read a code out to '
                                                  'someone on a phone call.',
                                            'hi': 'यह कोड दरवाज़े पर डिलीवरी वाले को, सामान हाथ में मिलने के बाद देना है। डिलीवरी '
                                                  'कोड ऐसे ही काम करता है। फ़ोन कॉल पर किसी को कोड न बताएं।'}}}

NEW_CATEGORIES = {'wrong_credit': {'priority': 88,
                                   'name': {'en': "Fake 'sent by mistake' money", 'hi': "'गलती से भेजे पैसे' वाली ठगी"},
                                   'actions': {'en': ["Check your balance in your bank's official app or passbook. A 'money credited' "
                                                      'SMS can be fake.',
                                                      'Do not send money back yourself. If money really came by mistake, the sender '
                                                      'should ask their own bank to reverse it.',
                                                      'If you already sent money, call 1930 at once.'],
                                               'hi': ["अपना बैलेंस बैंक के आधिकारिक ऐप या पासबुक में देखें। 'पैसे जमा हुए' वाला SMS "
                                                      'नकली हो सकता है।',
                                                      'खुद पैसे वापस न भेजें। अगर सच में गलती से पैसे आए हैं, तो भेजने वाला अपने बैंक '
                                                      'से वापस करवाए।',
                                                      'अगर पैसे भेज दिए हैं, तो तुरंत 1930 पर कॉल करें।']}},
                  'charity': {'priority': 58,
                              'name': {'en': 'Fake donation or charity appeal', 'hi': 'दान या चंदे की नकली अपील'},
                              'actions': {'en': ['Do not send money to a UPI ID or phone number given in a forwarded appeal.',
                                                 "To help a patient, give through the hospital's own account or a verified "
                                                 'fundraising page you can check.',
                                                 'If you already paid, call 1930; if not, report it on Chakshu at '
                                                 'sancharsaathi.gov.in.'],
                                          'hi': ['फॉरवर्ड की गई अपील में दिए UPI ID या फ़ोन नंबर पर पैसे न भेजें।',
                                                 'किसी मरीज़ की मदद करनी हो तो अस्पताल के अपने खाते से या किसी ऐसे फंडरेज़िंग पेज से '
                                                 'दें जिसकी आप जाँच कर सकें।',
                                                 'अगर पैसे भेज दिए हैं तो 1930 पर कॉल करें; नहीं तो sancharsaathi.gov.in पर चक्षु में '
                                                 'शिकायत करें।']}}}


# From the dev half of PublicBench v0 (real published messages), narrow wordings only; see the docstring.
REAL_MESSAGE_APPEND = {
    "threat_terms": ["report has been filed against you", "case has been filed against you",
                     "complaint has been filed against you", "fir has been filed against you", "court order against your",
                     "court order against you", "intelligence bureau", "pornographic", "porn videos", "porn sites",
                     "gandi film", "gandi filmen", "गंदी फिल्म", "गंदी फिल्में", "गंदी वीडियो", "अश्लील वीडियो", "अश्लील फिल्म"],
    "advance_fee": ["tax for releasing", "releasing the payment", "release the payment", "to release your payment",
                    "get tax", "transaction would cost you", "security fee", "सिक्योरिटी फीस", "clearance charges",
                    "clearance fee"],
    "prize": ["prize amount", "letter of guarantee", "lucky draw holder", "केबीसी", "भाग्यशाली ड्रा"],
    "emergency_terms": ["caught with", "has been caught", "been caught", "has been arrested", "was arrested",
                        "in police custody", "clear his name", "clear her name", "पकडा गया", "पकडी गई"],
    "money_send_terms": ["please pay", "pay him", "pay them", "pay her"],
    "sextortion_media": ["तस्वीर", "तस्वीरें", "तस्वीरों", "tasveer", "tasveeren"],
    "sextortion_threat": ["blackmail", "blackmailing", "ब्लैकमेल", "धमकी", "dhamki", "ऑनलाइन शेयर", "online share",
                          "सोशल मीडिया पर प्रसारित", "सोशल मीडिया पर डाल", "social media par daal", "social media pe daal",
                          "प्रसारित"],
    "code_phrases": ["the message i sent", "message i sent you", "sent you a message by mistake",
                     "accidentally sent you a message", "accidentally sent a message", "sent you an sms by mistake",
                     "accidentally sent you an sms", "sent you a code by mistake", "accidentally sent you a code",
                     "galti se message", "galti se code", "गलती से मैसेज", "गलती से कोड"],
    "share_verbs": ["dial the", "dial in the"],
    "investment": ["learning community", "stock enthusiasts", "stock selection methods", "high-quality stocks",
                   "want to invest in the stock market"],
}


def update(fraud: dict) -> None:
    lex = fraud["lexicons"]
    for name, words in NEW_LEXICONS.items():
        lex[name] = list(words)
    for appended in (APPEND_LEXICONS, REAL_MESSAGE_APPEND):
        for name, words in appended.items():
            lex[name] += [w for w in words if w not in lex[name]]
    fraud["signals"].update(NEW_SIGNALS)
    fraud["categories"].update(NEW_CATEGORIES)
    fraud["version"], fraud["date"] = "1.6.0", "2026-10-07"


def main() -> None:
    path = ROOT / "packs" / "fraud.v1.json"
    fraud = load(path)
    update(fraud)
    save(path, fraud)
    print("fraud 1.6.0 written; signed if this machine has the signer's key (SAHAYAK_SIGNER). Now run: python -m pytest")


if __name__ == "__main__":
    main()
