# -*- coding: utf-8 -*-
"""Builds the blind red-team set redteam_v1_blind.jsonl.

Every item carries an internal 'key' (used only for the build report); it is
dropped before writing. Items are shuffled with a fixed seed so that the id
order does not leak the label.
"""
import json
import random
import urllib.parse
from pathlib import Path

OUT = Path(__file__).parent / "redteam_v1_blind.jsonl"

ZW = "​"          # zero-width space
CA, CE = "а", "е"   # Cyrillic a, e
HDFC_EMOJI = "\U0001F177\U0001F173\U0001F175\U0001F172"  # negative-squared H D F C

def S(key, category, technique, lang, input_type, sender, text):
    return dict(key=key, label="scam", category=category, technique=technique,
                lang=lang, input_type=input_type, sender=sender, text=text)

def G(key, category, technique, lang, input_type, sender, text):
    return dict(key=key, label="genuine", category=category, technique=technique,
                lang=lang, input_type=input_type, sender=sender, text=text)

items = []

# =====================================================================
# SCAM - TEXT (non-regional, 73)
# =====================================================================
items += [
S("DA-T1", "digital_arrest",
  "Formal legal notice citing a real statute (BNSS); no link, no payment ask in this message - only a summons to a video 'statement' plus a secrecy order.",
  "en", "text", "+917428915063",
  "NOTICE U/S 35(3) BNSS - Central Bureau of Investigation, Economic Offences Wing, New Delhi.\nCase No. CBI/EOW/MUM/2026/7741\nYour Aadhaar-linked bank account has been flagged in an ongoing money laundering investigation. You are directed to give your statement through secure video conference today at 4:00 PM. This matter is CONFIDENTIAL; disclosing it to family members or bank staff will be treated as obstruction of investigation. Keep WhatsApp open on this number for the link.\n- Insp. R. K. Bhardwaj, CBI"),
S("DA-T3", "digital_arrest",
  "Follow-up to a call; polite; gives only bank-transfer details (no link, no UPI, no phone number). Signals are 'verification transfer, refunded later' and secrecy from the bank.",
  "en", "text", "+916280473915",
  "As discussed on the call, for completion of RBI fund verification kindly transfer the full FD amount to the supervisory account below. The amount will be auto-refunded within 72 hours after clearance from the Hon'ble Supreme Court.\nBeneficiary: Sarvottam Traders Pvt Ltd\nA/c No: 50200087431926\nIFSC: HDFC0004412\nPlease do not discuss this with your branch manager as he is also under investigation."),
S("DA-T4", "digital_arrest",
  "Link/QR is inside an image so the text has no URL; court-hearing-on-video framing in Hinglish.",
  "hinglish", "text", "+919065381472",
  "Aapke naam pe Supreme Court ka e-summons issue hua hai (Case No. 2291/2026, PMLA). Hearing aaj online hogi, judge sahab video call pe honge. Summons ki PDF dekhne ke liye photo me diye QR code ko scan karein. Hearing miss ki to non-bailable warrant jaari hoga. Ye case confidential hai, kisi ko batana mana hai."),
S("CC-T1", "courier_customs",
  "Link broken across two lines with an instruction to re-join it; host starts with the real brand ('indiapost.in-...').",
  "en", "text", "+918250937146",
  "IndiaPost: Your package is on hold at our warehouse because of incomplete address details. Please update your address within 12 hours or it will be returned to sender.\nhttps://indiapost.in-\nredelivery.top/IN\n(copy the full link into your browser)"),
S("CC-T2", "courier_customs",
  "Call-back number written with dots between every digit; courier hook that leads into a digital-arrest call.",
  "en", "text", "+917719083562",
  "FedEx Intl: Shipment AWB 7782 4410 9921 booked in your name to Taipei has been held by Mumbai Customs. Contents declared: 5 passports, 3 debit cards, 200g MDMA. If you did not book this parcel, call our customs desk on 9.1.3.6.4.0.2.8.7.5 within 2 hours, otherwise the case will be forwarded to the Narcotics Control Bureau."),
S("CC-T4", "courier_customs",
  "Tiny Rs 5 'redelivery fee' (card harvesting) in Devanagari; brand transliterated; link with spaces around the dot.",
  "hi", "text", "+919142760385",
  "डेल्हीवरी: पता अधूरा होने के कारण आपका पार्सल डिलीवर नहीं हो सका। दोबारा डिलीवरी के लिए केवल ₹5 शुल्क देकर पता अपडेट करें: dlvry-in . help/pay (स्पेस हटाकर खोलें)"),
S("EC-T1", "fake_echallan",
  "Cyrillic look-alike letters inside 'mParivahan', 'e-challan' and 'vehicle' defeat keyword matching; header-style sender; look-alike gov domain.",
  "en", "text", "VK-PRVHAN-S",
  f"mP{CA}riv{CA}h{CA}n: An e-ch{CA}ll{CA}n No. DL116457823091 of Rs.1000/- has been issued against your v{CE}hicl{CE} for over-speeding on 03/10/2026. Pay within 3 days to avoid court proceedings and licence suspension: https://echallan-parivahan.gov-in.org.in/pay"),
S("EC-T2", "fake_echallan",
  "Malicious APK attachment presented as a challan receipt; no link or phone number in the text.",
  "hinglish", "text", "+917032694158",
  "RTO Traffic Challan 🚦\nAapki gaadi ka ₹2000 ka challan kata hai. Photo proof aur receipt niche file me hai, download karke check karein 👇\n📎 RTO_Challan_Receipt.apk (6.2 MB)"),
S("EC-T4", "fake_echallan",
  "Piggybacks on real Lok Adalat challan-settlement drives; small 'registration fee' to a UPI ID; no link.",
  "hi", "text", "+918858136027",
  "राष्ट्रीय लोक अदालत 11 अक्टूबर: आपके वाहन के लंबित चालान ₹3,000 पर 70% तक छूट। स्लॉट बुक करने के लिए ₹199 पंजीकरण शुल्क इस UPI पर भेजें: lokadalat.challan@sahayakdemo — बुकिंग केवल आज तक।"),
S("UT-T1", "utility_disconnection",
  "Classic electricity script, but the call-back number is spelled as a mix of words and digits.",
  "en", "text", "+918167304925",
  "Dear Consumer, your electricity power will be disconnected tonight at 9.30 PM from electricity office because your previous month bill was not updated. Please immediately contact our electricity officer nine eight one 0 two four seven 3 six five. Thank you"),
S("UT-T3", "utility_disconnection",
  "Emerging prepaid smart-meter pretext (real rollout); short, technical, plausible negative balance; header-style sender.",
  "hi", "text", "AD-SMTMTR-S",
  "स्मार्ट मीटर अलर्ट: आपके प्रीपेड स्मार्ट मीटर का बैलेंस -₹23.40 हो गया है। 1 घंटे में बिजली आपूर्ति अपने आप बंद हो जाएगी। तुरंत रिचार्ज करें: smartmeter-recharge.online/up"),
S("UT-T4", "utility_disconnection",
  "Water-board version of the disconnection script; consumer-number detail adds credibility; WhatsApp-only contact.",
  "hinglish", "text", "+917065239418",
  "Jal Board Notice: Aapke ghar (K No. 2104875520) ki water supply kal subah 7 baje band kar di jayegi kyunki ₹3,214 ka bill pending hai. Connection kaatne aur meter seal se bachne ke liye JE Sharma ji se turant WhatsApp pe sampark karein: 70652 39418"),
S("UT-T5", "utility_disconnection",
  "Exploits the 2026 LPG-shortage news (gas eKYC); APK attachment; no link or number.",
  "hinglish", "text", "+919327105846",
  "Indane Gas ⚠️ LPG supply limited hai. Sirf eKYC completed customers ko hi next cylinder milega. Aapka eKYC pending hai - niche wali file download karke 2 minute me complete karein warna booking cancel ho jayegi.\n📎 Gas_KYC_Update.apk"),
S("KY-T1", "kyc_update",
  "Terse SMS-speak with spaced-out key words ('Y O N O', 'P A N') and misspellings (blokd, Updt) to dodge keyword lists.",
  "en", "text", "+916371904258",
  "SBI: Ur Y O N O a/c will be blokd 2day. Updt P A N now 👉 sbi-yono-pan.co/u"),
S("KY-T2", "kyc_update",
  "Abuses the genuine RBI move to .bank.in domains: URL begins with the real 'hdfc.bank.in' but the registered domain is reverify-kyc.com; look-alike header (HDFCBN).",
  "en", "text", "JM-HDFCBN-S",
  "HDFC Bank: As per the RBI mandate, all customers must re-verify KYC on our new secure .bank.in website by 10-Oct-2026, else debit freeze will apply. Verify now: https://hdfc.bank.in.reverify-kyc.com/login"),
S("KY-T3", "kyc_update",
  "Twists real UIDAI advice (update every 10 years); link split over three lines with an instruction to join them.",
  "hi", "text", "+918436192057",
  "UIDAI सूचना: आपका आधार 10 साल पुराना है और अपडेट न होने के कारण 15 अक्टूबर से निष्क्रिय कर दिया जाएगा। मुफ्त अपडेट के लिए यहाँ जाएँ:\nmyaadhaar-update\n.\nonline\n(तीनों लाइन जोड़कर खोलें)"),
S("KY-T4", "kyc_update",
  "Real government initiative (PAN 2.0) used as bait; 'free' framing, URL shortener, OTP asked casually at the end.",
  "hinglish", "text", "+919504178263",
  "PAN 2.0 launch ho gaya hai! Purana PAN 31 Dec ke baad invalid ho jayega. QR code wala naya e-PAN FREE download karein 👉 tinyurl.com/epan2-new-qr\nSirf Aadhaar number aur aaya hua OTP daalna hai."),
S("KY-T6", "kyc_update",
  "Invisible zero-width spaces inside 'KYC', 'expired' and 'blocked'.",
  "en", "text", "+917894035126",
  f"Paytm: Your wallet K{ZW}Y{ZW}C has e{ZW}xpired. Your account will be b{ZW}locked in 24 hrs. Re-verify with Aadhaar now: ptm-kyc.help/a"),
S("FT-T1", "fastag_annual_pass",
  "Impersonates a real 2025-26 product (NHAI/I4C warned about fake annual-pass sites); discount lure, no threat; look-alike of the official RajmargYatra name.",
  "en", "text", "+918805316274",
  "NHAI FASTag Annual Pass: Festive offer ₹1,999 only (regular ₹3,000), valid for 200 toll crossings or 1 year. Activate on your vehicle before 15 Oct to avail the discount: rajmarg-yatra-pass.in/activate"),
S("AP-T2", "malicious_apk",
  "Framed as a protective security step, not a payment; urgency plus URL shortener to an app.",
  "en", "text", "+916203917485",
  "ALERT: Suspicious login detected on your ICICI net banking from Lucknow. To secure your account, install our official 'iSecure Shield' protection app within 1 hour: bit.ly/iSecureShield26\n- ICICI Fraud Prevention Cell"),
S("AP-T3", "malicious_apk",
  "Mirrors the Jan-2026 fake 'SBI Aadhaar update APK' (PIB fact-checked); Hindi with an APK attachment, no link.",
  "hi", "text", "+917488302619",
  "प्रिय ग्राहक, RBI के नए नियम के अनुसार बैंक खाते में आधार अपडेट अनिवार्य है। SBI आधार अपडेट ऐप डाउनलोड करके अपडेट करें, वरना आपका खाता आज रात 12 बजे फ्रीज़ हो जाएगा।\n📎 SBI_Aadhaar_Update.apk"),
S("AP-T4", "malicious_apk",
  "Emerging 2026 lure aimed at government staff; no threat, no money ask - only 'check your salary' + APK + forward request.",
  "en", "text", "+919871203546",
  "8th Pay Commission: Check your revised salary, DA & arrears instantly 👇 For central govt employees and pensioners only.\nOfficial DoPT calculator app: 8thCPC_Salary_Calculator.apk ✅\nPlease forward to your department group."),
S("AP-T5", "malicious_apk",
  "Scam wrapped in a genuine-sounding awareness message: repeats real advice ('no bank asks for OTP') before pushing an app; Hindi.",
  "hi", "text", "+918130947265",
  "साइबर दोस्त अलर्ट 🚨 ठगों से सावधान! कोई भी बैंक या पुलिस कभी OTP या पिन नहीं मांगती। अपने मोबाइल और बैंक खाते को ठगी से सुरक्षित रखने के लिए सरकार का 'साइबर सुरक्षा कवच' ऐप अभी इंस्टॉल करें 👉 cyberdost-kavach.in/app — यह संदेश सभी परिवार वालों को भेजें।"),
S("AI-T1", "apk_invite",
  "Warm personal wedding invitation; the only signal is the .apk file extension.",
  "hinglish", "text", "+918962047315",
  "Namaste 🙏 Aap sabhi ko hamari beti Pooja ki shaadi me saadar amantrit karte hain - 24 November, Indore. Shaadi ka card niche hai, zaroor aaiyega 💐\n📎 Pooja_weds_Rohit_Card.apk"),
S("AI-T2", "apk_invite",
  "Business-like, very short; double file extension (.pdf.apk) hides the APK.",
  "en", "text", "+917350196284",
  "Sir, sending the land registry documents you asked for. Please check and confirm by evening.\n📎 Registry_Documents_Final.pdf.apk"),
S("IN-T1", "investment_scam",
  "Polished, calm group-admin tone; imitates a real broker brand; 'guaranteed allotment' via 'institutional account' is the main tell.",
  "en", "text", "+918248613097",
  "Good morning members ☀️ Today's IPO subscription through our Institutional Account (QIB quota) - guaranteed allotment, listing gain expected 60-80%. Members who wish to participate, kindly deposit funds in your 'HDFC Sky Pro' institutional wallet before 2 PM. Contact Assistant Ananya for the receiving account details.\n- Prof. Rajiv Mehra, SEBI Reg. Research Analyst"),
S("IN-T3", "investment_scam",
  "No link or number; formal; 'pay tax before you can withdraw' is the classic exit-stage tell.",
  "en", "text", "+917019482653",
  "Dear Investor, your Century Pro account balance is ₹18,42,600. Your withdrawal request cannot be processed until 20% capital gains tax (₹3,68,520) is cleared as per SEBI rules. Kindly deposit the tax amount within 24 hrs to avoid account freeze."),
S("CR-T2", "crypto",
  "Cloud-mining Ponzi; small deposit, 10%/day return; reads like an ordinary app ad.",
  "hinglish", "text", "+916355210947",
  "Bitcoin mining app se ghar baithe kamao 💰 ₹599 deposit karo, roz ₹60 milenge. Refer karne pe extra bonus. Withdrawal turant UPI me.\nApp: btc-minepro.app  |  Invite code: 77831"),
S("CR-T3", "crypto",
  "Wrong-number opener of a pig-butchering scam: no link, no money, no number - only a social hook. Expected verdict at least Suspicious.",
  "en", "text", "+919632048175",
  "Hi Mr. Arjun, this is Neha from the Gold & Crypto Investors Club. Our call is shifted to 7 pm today. Oh sorry, I think I have the wrong number 😅 Anyway, nice to meet you! Are you also into trading?"),
S("TJ-T1", "task_job",
  "Looks like a normal recruiter message; no fee or link yet; the tell is unrealistic pay for minimal work.",
  "en", "text", "+918340915276",
  "Hi, I'm Priya from Talent Bridge HR. We found your profile on Naukri. We're hiring for a flexible part-time role - 30 to 60 minutes daily, ₹2,000-₹5,000 per day, simple online tasks from your phone. Can I share the details?"),
S("TJ-T2", "task_job",
  "Short; reply-YES call to action; no link or number.",
  "hinglish", "text", "+917208516943",
  "YouTube video like karo aur har like pe ₹50 pao 👍 Roz 20 task = ₹1000. Pehle 3 task ka payment turant. Shuru karne ke liye 'YES' reply karein."),
S("TJ-T3", "task_job",
  "Mid-scam message using the scheme's own jargon ('task wallet', 'welfare task'); no link.",
  "hinglish", "text", "+919718205364",
  "Congratulations! Aapke 3 task complete hue, ₹450 commission aapke task wallet me credit ho gaya. Ab 'Welfare Task' hai: ₹3,000 deposit karo aur 10 minute me ₹4,100 wapas pao. Payment details receptionist share karegi."),
S("FJ-T1", "fake_job_fee",
  "Real-company offer-letter format; the fee is called a 'refundable security amount'.",
  "en", "text", "+919045318726",
  "Dear Candidate, Congratulations! You have been selected for the post of Customer Support Executive at Reliance Retail Ltd, Pune. CTC ₹3.6 LPA. Your offer letter is attached. To confirm joining, deposit the refundable training kit & laptop security amount of ₹4,850 within 48 hours.\nHR Department"),
S("FJ-T2", "fake_job_fee",
  "Phone number with every digit spaced; small 'uniform/ID card' fee.",
  "hinglish", "text", "+918439027715",
  "Amazon Warehouse Bhiwandi me direct joining 💼 Salary ₹18,500 + PF + room. Koi interview nahi. Bas ID card aur uniform ka ₹1,200 jama karna hai. Seats limited!\nCall/WhatsApp: 8 4 3 9 0 2 7 7 1 5"),
S("MU-T1", "mule_account",
  "Money-mule recruitment dressed as passive income and claimed to be legal; no link.",
  "hinglish", "text", "+917330928516",
  "Part-time income ₹15,000/month 💸 Bas apna savings ya current account hamari gaming company ke payments ke liye rent pe do. Koi kaam nahi, sirf net banking aur SIM share karni hai. 100% legal, payout har mahine 1 tarikh ko. Telegram pe 'RENT' bhejo: @PayoutPartner"),
S("LN-T1", "loan_fee",
  "Pre-approved loan with an upfront 'file processing' fee; looks like an NBFC sanction SMS.",
  "en", "text", "+916352097184",
  "Congratulations! Your pre-approved personal loan of ₹3,00,000 @ 9.5% p.a. is sanctioned. No CIBIL check. Pay only ₹2,499 file processing charge to release funds today.\nSanction letter: dhankuber-finserv.in/sl/88213"),
S("LN-T2", "loan_app_extortion",
  "Illegal loan-app recovery threat (morphed photos to contacts) rather than a fee lure.",
  "hinglish", "text", "+919608123754",
  "Tumhara loan overdue hai ₹3,850. Aaj 6 baje tak payment nahi kiya to tumhari photo edit karke tumhare saare contacts ko bhej denge. Payment link: pay-loanx.in/lnx992"),
S("CS-T1", "fake_customer_care",
  "Replies to a real complaint the user posted publicly; friendly; moves the victim to WhatsApp and asks for UPI ID.",
  "en", "text", "+918961044273",
  "Hi, this is Swiggy Support. We saw your post about the refund that hasn't come. Sorry for the trouble! To process it faster, please WhatsApp our refund desk on 89610 44273 with your UPI ID and registered mobile number."),
S("CS-T2", "fake_customer_care",
  "Copies a genuine debit-alert format; only tells are the 10-digit mobile 'helpline' and a 10-digit sender. Pairs with genuine alerts in this set.",
  "en", "text", "+919046112785",
  "Rs.49,999.00 debited from A/c XX4417 on 07-10-26 for APPLE STORE ONLINE. If not done by you, call 9046112785 immediately to block card & reverse the amount. -HDFC Bank"),
S("RF-T1", "refund_sent_by_mistake",
  "Emotional plea, no link; relies on a fake credit SMS sent earlier.",
  "hinglish", "text", "+917488905213",
  "Sir galti se aapke number pe ₹5,000 chale gaye, aapko SMS aaya hoga. Meri beti ki school fees thi 🙏 please wapas bhej do isi number pe GPay, bahut zaroorat hai. Bhagwan aapka bhala kare."),
S("RF-T2", "refund_collect_request",
  "Since P2P collect requests ended (Oct 2025) the request poses as a 'merchant'; 'enter PIN to receive' is the tell.",
  "en", "text", "+918296013457",
  "Your refund of ₹1,850 for cancelled order #FK4471 is ready. A payment request from 'Flipkart Refund Desk' has been sent to your UPI app. Approve it and enter your UPI PIN to receive the amount in your bank account."),
S("UQ-T2", "upi_scan_to_receive",
  "Scan-to-receive with the QR inside an image; no link or number in the text.",
  "en", "text", "+919354017286",
  "🎉 Diwali Cashback Bonanza! You've won ₹2,999 PhonePe cashback. Scan the QR code in the image to receive it instantly in your bank account. Offer valid today only."),
S("UQ-T3", "upi_scan_to_receive",
  "Very short Hindi mixing Devanagari with English UI words.",
  "hi", "text", "+917417290538",
  "आपका ₹1,500 का रिफंड भेजना है। मेरे भेजे हुए QR को स्कैन करें और 'Receive' करने के लिए अपना UPI पिन डालें।"),
S("SS-T1", "sim_swap_esim",
  "Tells the victim to message the operator's real short code (121) - looks legitimate - but with the scammer's email, which hands over the eSIM.",
  "en", "text", "+917290418536",
  "Airtel: Your physical SIM will be deactivated on 10-Oct as part of 5G eSIM migration. To keep your number active, SMS  eSIM esimdesk.update@gmail.com  to 121 now. Ignore and lose service."),
S("CF-T1", "call_forwarding",
  "USSD call-forwarding code disguised as a delivery-reschedule step; no link, money, OTP or threat.",
  "en", "text", "+918708134296",
  "Blue Dart: Delivery attempted, customer not reachable. To reschedule, dial *21*7428015963# from your registered mobile and our executive will call you back."),
S("RE-T1", "relative_emergency",
  "Normal family tone; signals are new number + urgency + 'don't tell Papa'.",
  "hinglish", "text", "+919358027461",
  "Mummy ye mera naya number hai, purana phone gir ke toot gaya. Ek urgent kaam hai, ₹15,000 bhej do abhi is UPI pe: rahul.k.2026@sahayakdemo. Papa ko mat batana please, shaam ko sab bataunga ❤️"),
S("RE-T2", "account_takeover_otp",
  "Arrives from a friend's (hijacked) WhatsApp; never says 'OTP' - 'a 6-digit code'.",
  "en", "text", "+919819304725",
  "Hey! Sorry to bother you, I accidentally sent a 6-digit code to your number instead of mine 🙈 Can you forward it to me quickly? It's a bit urgent, I'm locked out."),
S("OF-T1", "account_takeover_otp",
  "Copies the genuine UIDAI OTP template (a real one is in this set) and adds 'forward this SMS to cancel'; sent from a mobile number.",
  "en", "text", "+917061482935",
  "OTP for Aadhaar (XX7712) is 590318 (valid for 10 mins). Do not share this OTP with anyone. If you have NOT requested this, your Aadhaar may be misused - to cancel the request immediately, forward this SMS to 7061482935. -UIDAI"),
S("RE-T3", "boss_impersonation",
  "'Boss scam' (I4C advisory 2026); Hindi; gift-card codes + secrecy; no link.",
  "hi", "text", "+917039518264",
  "नमस्ते, मैं एक मीटिंग में हूँ, कॉल नहीं ले सकता। एक ज़रूरी काम है — ₹10,000 वाले 5 Amazon गिफ्ट कार्ड अभी खरीदकर उनके कोड इसी नंबर पर भेज दो, शाम को ऑफिस से रीइंबर्स कर दूँगा। इस बारे में किसी से बात मत करना। — शर्मा सर"),
S("AO-T2", "army_olx_buyer",
  "Bulk-order bait for a small business; CVV requested as 'the 3 numbers on the back of the card'.",
  "hinglish", "text", "+916239104857",
  "Namaste ji, main Army se Capt. Sharma bol raha hoon. Unit ke 40 jawanon ke liye aapke dhabe se 3 din ka khana book karna hai. Payment Army canteen account se hogi, uske liye aapka card verify karna padega - card ke peeche wale 3 number bata dijiye."),
S("RP-T2", "rent_property_advance",
  "Property token-advance lure; 'no site visit needed' is the tell; Hindi, no link.",
  "hi", "text", "+918115027394",
  "अयोध्या राम मंदिर से सिर्फ 3 किमी पर रजिस्ट्री वाला प्लॉट, मात्र ₹4.5 लाख में। आज ₹21,000 टोकन देकर बुक करें, कल से रेट बढ़ जाएंगे। साइट विज़िट की ज़रूरत नहीं, सारे कागज़ व्हाट्सएप पर भेज देंगे।"),
S("SX-T1", "sextortion",
  "Pure threat, no link or account; relies on shame.",
  "hinglish", "text", "+919471830256",
  "Tumhari video call ki recording mere paas hai 😈 2 ghante me ₹21,000 bhejo warna tumhare saare Facebook friends aur family group me bhej dungi. Upar screenshot dekh lo."),
S("SX-T2", "sextortion",
  "Shame + legal threat in official police tone; no link or number (victim is expected to reply).",
  "en", "text", "+917827340169",
  "Cyber Crime Cell, Delhi Police: Your mobile IP was found accessing child sexual abuse material on 05/10/2026. An FIR under the POCSO Act and IT Act Sec 67B is being registered. To close the matter without arrest, pay the fine of ₹29,500 within 6 hours. Case officer: ACP Rajesh Verma."),
S("LT-T1", "lottery_kbc",
  "Claim number spelled out in romanised Hindi words; details 'in the photo'.",
  "hinglish", "text", "+917340918265",
  "KBC Jio Lucky Draw 2026 🎉 Aapke number ne ₹25,00,000 jeete hain! Lottery No. 8865. Poori details photo me hai. Prize claim karne ke liye manager Rana Pratap Singh ko sirf WhatsApp call karein: nau aath saat do, chhe paanch chaar teen, ek shunya."),
S("GS-T1", "govt_scheme",
  "Real scheme and timing (next PM-KISAN instalment); APK attachment widely reported in 2025-26.",
  "hi", "text", "+916202813574",
  "पीएम किसान सम्मान निधि: अगली किस्त ₹2,000 जारी। जिन किसानों का ई-केवाईसी अधूरा है उनकी किस्त रुकी हुई है। नीचे दिया गया PM Kisan ऐप इंस्टॉल करके तुरंत ई-केवाईसी करें।\n📎 PM_KISAN_eKYC.apk"),
S("GS-T2", "govt_scheme",
  "Real 2024-25 scheme (Vay Vandana, 70+); small 'printing & speed-post' fee for a card that is free.",
  "en", "text", "+919827301546",
  "Ayushman Vay Vandana Card for senior citizens 70+: ₹5 lakh free treatment. Your father's card has been approved. Pay ₹350 card printing & speed-post charges to get it delivered at home. UPI: ayushman.card@sahayakdemo"),
S("GS-T3", "govt_scheme",
  "Viral forward with no fee or threat; harvests numbers/data; says 'free' instead of 'pay'.",
  "hinglish", "text", "+918604193725",
  "*PM Free Recharge Yojana 2026* 🇮🇳\nSabhi Bharatiyon ko 3 mahine ka ₹799 wala recharge bilkul FREE. Last date aaj hai. Apna number register karein 👇\nfreerecharge-yojana.in\n_Forwarded many times_"),
S("GS-T4", "govt_scheme",
  "Official Hindi tone; small 'bank verification fee'; call-back to a 'district officer' mobile.",
  "hi", "text", "+919471228309",
  "राष्ट्रीय छात्रवृत्ति पोर्टल: बधाई हो! आपके बच्चे का चयन 2026-27 की प्री-मैट्रिक छात्रवृत्ति ₹12,000 के लिए हुआ है। राशि जारी करने हेतु 10 अक्टूबर से पहले ₹250 बैंक सत्यापन शुल्क जमा करना होगा। जिला छात्रवृत्ति अधिकारी से संपर्क करें: 9471228309"),
S("GS-T5", "govt_scheme",
  "Timed to the real Oct-Nov life-certificate season; look-alike of the official jeevanpramaan.gov.in.",
  "en", "text", "+917765019328",
  "Dear Pensioner, your Jeevan Pramaan (Life Certificate) for 2026 is pending. Your pension will be stopped from Nov-2026. Submit online from home in 2 minutes: jeevanpramaan-online.co.in\n- Office of CPAO"),
S("GS-T7", "govt_scheme",
  "Uses the real RBI UDGAM unclaimed-deposits portal name; tiny percentage 'processing fee'; no link.",
  "en", "text", "+918920471365",
  "RBI UDGAM: An unclaimed deposit of ₹48,620 has been found in your name (old SB account, Bank of India). As per RBI circular, pay 2% processing fee ₹972 to release the amount to your current account. Claim ID: UDG/26/77104."),
S("CH-T1", "fake_charity",
  "Emotional appeal indistinguishable in tone from real crowdfunding; personal UPI ID; forward-to-10-groups request.",
  "en", "text", "+919137560248",
  "🙏 Please help 4-year-old Aarav fighting blood cancer at Tata Memorial, Mumbai. He needs ₹18 lakh for a bone-marrow transplant in 3 days. Every ₹100 counts. Donate via UPI: helpaarav@sahayakdemo. Please forward to at least 10 groups 🙏"),
S("CH-T2", "fake_charity",
  "Religious-trust framing and an 80G tax-exemption claim; pays to a personal mobile number.",
  "hi", "text", "+917347902118",
  "बाढ़ पीड़ितों के लिए राहत सामग्री — गुरुद्वारा सेवा समिति। अपना योगदान सीधे इस नंबर पर PhonePe करें: 7347902118। आपका दान 80G के तहत टैक्स छूट योग्य है। वाहेगुरु मेहर करें 🙏"),
S("GJ-T1", "fake_govt_job",
  "'No exam' government job; medical/verification fee; spaced digits.",
  "hinglish", "text", "+919125634078",
  "Railway Group D Bharti 2026 🚆 Bina pariksha seedhi bharti, sirf 10th pass. Joining letter 15 din me. Medical aur verification fees ₹15,500. Seat confirm karne ke liye Railway Board officer Mr. Tiwari se WhatsApp karein: 9 1 2 5 6 3 4 0 7 8"),
S("GJ-T2", "fake_govt_job",
  "Mimics the real GDS merit-list process in Hindi; adds a non-existent document-verification fee.",
  "hi", "text", "+918303917642",
  "इंडिया पोस्ट GDS मेरिट लिस्ट 2026: सीतापुर डिवीजन की तीसरी मेरिट लिस्ट में ग्रामीण डाक सेवक पद हेतु आपका नाम है। दस्तावेज़ सत्यापन शुल्क ₹2,800 दिनांक 09-10-2026 तक जमा करें। नियुक्ति पत्र डाउनलोड करें: indiapost-gds-result.in/dv"),
S("IT-T1", "income_tax_refund",
  "URL begins with the real 'incometax.gov.in' but the registered domain is refund-validate.in; header-style sender; timed to refund season.",
  "en", "text", "VM-ITREFD-S",
  "Income Tax Department: Your refund of ₹15,490 for AY 2026-27 is pending due to bank account validation failure. Re-validate within 24 hrs to avoid cancellation: https://incometax.gov.in.refund-validate.in/efile"),
S("IT-T2", "income_tax_refund",
  "Asks for 'the code that came on your mobile' (never says OTP); WhatsApp number written in Hindi words.",
  "hi", "text", "+918294017365",
  "आयकर विभाग: आपका ₹8,250 का टैक्स रिफंड स्वीकृत हो गया है। राशि आपके खाते में भेजने के लिए अपना बैंक खाता नंबर और मोबाइल पर आया कोड इस नंबर पर व्हाट्सएप करें: आठ दो नौ चार शून्य एक सात तीन छह पाँच"),
S("RW-T1", "reward_points",
  "Brand written in enclosed-letter emoji characters (not ASCII); look-alike domain.",
  "en", "text", "+917208439615",
  f"{HDFC_EMOJI} Credit Card: Your 7,850 reward points (worth ₹7,850) expire TODAY. Redeem as cash to your account: hdfcrewards.in-redeem.top"),
S("RW-T2", "reward_points",
  "Shortened link; asks for card details in order to 'receive' cashback.",
  "hinglish", "text", "+919064823517",
  "Aapke Airtel Thanks ke 2,450 points aaj raat expire ho jayenge 😱 Inhe ₹2,450 cashback me badlo. Link me jaakar apne debit card ki details daalein: is.gd/airtelpts"),
S("MT-T1", "matrimonial",
  "Long, romantic, respectful; the money ask is deferred to a future 'customs' call.",
  "en", "text", "+917703916258",
  "Hi Pooja ji, I saw your profile on the matrimony site. I'm Dr. Aakash Malhotra, a cardiologist in London. My family is very traditional and I really liked your values. I am coming to India next month to meet your parents. I have sent you a small gift (gold set + iPhone) by courier - the agency may call you for small customs charges, please manage it, I will return it when I come."),
S("MT-T2", "matrimonial",
  "Romance-to-investment (pig-butchering) in Hindi with no link or amount yet.",
  "hi", "text", "+919370418256",
  "नमस्ते, मैं स्नेहा, सिंगापुर में रहती हूँ। मैट्रिमोनी साइट पर आपकी प्रोफाइल देखी, आप बहुत सुलझे हुए लगे। मेरे मामा जी एक गोल्ड ट्रेडिंग प्लेटफॉर्म चलाते हैं, मैं हर हफ्ते 20% कमाती हूँ। आप चाहें तो मैं आपको भी सिखा सकती हूँ, बस एक छोटा अकाउंट खोलना है।"),
S("EX-1", "pilgrimage_booking",
  "Real seasonal demand (Kedarnath closes after Diwali); claims 'authorised agent' status; official bookings are only via IRCTC HeliYatra.",
  "en", "text", "+919568013724",
  "Kedarnath Heli Service (Pawan Hans authorised agent): Last 4 seats for 18 Oct from Phata helipad, ₹6,200 per person (return). Book now by paying 50% advance on UPI; ticket PDF on WhatsApp within 10 minutes. Season closing soon!"),
S("EX-4", "recovery_scam",
  "Targets people who already lost money; cites the real NCRP complaint-number format and a 'court order'.",
  "hinglish", "text", "+916205913447",
  "Cyber Crime Recovery Cell (NCRP): Aapki complaint no. 31710260078842 (online fraud, ₹65,000) process ho gayi hai. Fraudster ke account se paisa recover ho gaya hai. Refund release karne ke liye court order ke anusaar 10% clearance charge jama karna hoga. SI Meena se WhatsApp pe sampark karein: 62059 13447"),
S("EX-6", "voter_sir_otp",
  "Rides on the real nationwide SIR electoral-roll exercise; 'losing your vote' fear; OTP via link.",
  "en", "text", "+918340271956",
  "Election Commission - SIR 2026: Your name is marked 'Duplicate/Shifted' in the draft electoral roll and will be deleted on 15 Oct. To retain your vote, verify through the BLO link and enter the OTP you receive: voters-sir-verify.in/epic"),
]

# =====================================================================
# SCAM - TEXT (regional, 12)
# =====================================================================
items += [
S("R-ta-T", "task_job",
  "Tamil script; task-scam pitch with only a Telegram handle (no link, no fee yet).",
  "ta", "text", "+916380249157",
  "வணக்கம்! வீட்டிலிருந்தே பகுதிநேர வேலை 🏠 தினமும் 30 நிமிடம் YouTube வீடியோக்களுக்கு லைக் போட்டால் போதும். ஒரு லைக்கிற்கு ₹50, தினமும் ₹1,500 முதல் ₹3,000 வரை சம்பாதிக்கலாம். முதல் 3 டாஸ்க்குகளுக்கு உடனே பணம் கிடைக்கும். ஆர்வம் இருந்தால் Telegram-இல் @TamilJobs_Priya-வை தொடர்பு கொள்ளவும்."),
S("R-te-T", "loan_fee",
  "Telugu script; '₹2,999 insurance charge' before disbursal; spaced digits.",
  "te", "text", "+917993104628",
  "అభినందనలు! మీకు ₹5,00,000 పర్సనల్ లోన్ ముందస్తుగా ఆమోదించబడింది. CIBIL స్కోర్ అవసరం లేదు, డాక్యుమెంట్లు అవసరం లేదు. డబ్బు ఈరోజే మీ ఖాతాలో జమ కావాలంటే ముందుగా ₹2,999 ఇన్సూరెన్స్ ఛార్జ్ చెల్లించండి. వివరాలకు WhatsApp చేయండి: 7 9 9 3 1 0 4 6 2 8"),
S("R-bn-T", "kyc_update",
  "Bengali script with Bengali numerals; link with spaces around the dot and an instruction to remove them.",
  "bn", "text", "+918017342596",
  "প্রিয় গ্রাহক, আপনার ব্যাংক অ্যাকাউন্টের KYC-র মেয়াদ শেষ হয়ে গেছে। আজ রাত ১২টার মধ্যে আপডেট না করলে অ্যাকাউন্ট ফ্রিজ হয়ে যাবে। এখনই PAN ও আধার দিয়ে আপডেট করুন: kyc-update-bank . in/wb (স্পেস বাদ দিয়ে খুলুন)"),
S("R-mr-T1", "govt_scheme",
  "Marathi; Ladki Bahin eKYC (a real 2025-26 requirement) with a fake 'gov.in'-looking domain; asks Aadhaar + OTP. Pairs with a genuine Ladki Bahin credit SMS.",
  "mr", "text", "+919307218465",
  "लाडकी बहीण योजना: आपली ई-केवायसी अपूर्ण असल्याने ऑक्टोबर महिन्याचा ₹१,५०० चा हप्ता थांबवण्यात आला आहे. हप्ता पुन्हा सुरू करण्यासाठी खालील लिंकवर आधार क्रमांक व OTP टाकून २४ तासांत ई-केवायसी पूर्ण करा: ladkibahin-ekyc.maha-gov.in.net"),
S("R-mr-T2", "utility_disconnection",
  "Marathi MSEB script; phone number in Devanagari (Marathi) numerals so digit regexes miss it.",
  "mr", "text", "+918421097356",
  "प्रिय ग्राहक, आपले मागील महिन्याचे वीज बिल अपडेट न झाल्यामुळे आज रात्री ९:३० वाजता महावितरण कार्यालयाकडून आपला वीज पुरवठा खंडित केला जाईल. कृपया त्वरित आमच्या वीज अधिकाऱ्यांशी संपर्क साधा: ९८२२० ४१७६३. धन्यवाद."),
S("R-gu-T", "investment_scam",
  "Gujarati; link is a real WhatsApp group-invite domain (chat.whatsapp.com), so domain checks pass; 'guaranteed' monthly profit is the tell.",
  "gu", "text", "+919727410586",
  "નમસ્તે 🙏 અમારા ફ્રી શેરબજાર WhatsApp ગ્રુપમાં જોડાઓ. રોજ 2-3 ખાતરીવાળી ટીપ્સ, દર મહિને 30% નફો પાક્કો. ગઈકાલે સભ્યોએ ₹1.8 લાખ કમાયા. મર્યાદિત જગ્યા, આજે જ જોડાઓ: chat.whatsapp.com/Gx7StockGuruVIP"),
S("R-kn-T", "fake_echallan",
  "Kannada; traffic-challan APK attachment, court-notice threat.",
  "kn", "text", "+917204913856",
  "ಸಂಚಾರ ಪೊಲೀಸ್ ಸೂಚನೆ: ನಿಮ್ಮ ವಾಹನದ ಮೇಲೆ ₹1,000 ಟ್ರಾಫಿಕ್ ಚಲನ್ ಬಾಕಿ ಇದೆ. ಇಂದು ಪಾವತಿಸದಿದ್ದರೆ ನ್ಯಾಯಾಲಯದ ನೋಟಿಸ್ ಕಳುಹಿಸಲಾಗುವುದು. ಚಲನ್ ವಿವರ ಮತ್ತು ಫೋಟೋ ನೋಡಲು ಕೆಳಗಿನ ಫೈಲ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ 👇\n📎 KA_Traffic_Challan.apk"),
S("R-ml-T1", "lottery_kbc",
  "Malayalam; Kerala-lottery 'online draw' (no such thing) with a GST fee; spaced digits.",
  "ml", "text", "+918075329146",
  "അഭിനന്ദനങ്ങൾ! 🎉 കേരള ഭാഗ്യക്കുറി ഓൺലൈൻ നറുക്കെടുപ്പിൽ നിങ്ങളുടെ മൊബൈൽ നമ്പറിന് ₹25 ലക്ഷം സമ്മാനം ലഭിച്ചിരിക്കുന്നു. സമ്മാനത്തുക ബാങ്ക് അക്കൗണ്ടിലേക്ക് ലഭിക്കാൻ ₹8,500 GST ഫീസ് അടയ്ക്കുക. കൂടുതൽ വിവരങ്ങൾക്ക് ലോട്ടറി ഓഫീസറെ WhatsApp ചെയ്യുക: 8 0 7 5 3 2 9 1 4 6"),
S("R-ml-T2", "fake_job_fee",
  "Malayalam; Gulf nurse job with 'no interview' and a large visa/medical advance - common Kerala pattern.",
  "ml", "text", "+919562018347",
  "ദുബായിലെ പ്രമുഖ ആശുപത്രിയിൽ സ്റ്റാഫ് നഴ്സ് ഒഴിവുകൾ. ശമ്പളം AED 6,500 + താമസം + ടിക്കറ്റ് സൗജന്യം. ഇന്റർവ്യൂ ഇല്ല, നേരിട്ട് നിയമനം. വിസ പ്രോസസ്സിംഗിനും മെഡിക്കലിനുമായി ₹35,000 മുൻകൂറായി അടയ്ക്കണം. ഓഫർ ലെറ്റർ ഇന്നുതന്നെ അയയ്ക്കാം. ബന്ധപ്പെടുക: ജോസഫ് സർ, 9562018347"),
S("R-pa-T", "relative_emergency",
  "Punjabi (Gurmukhi); 'nephew in Canada' new-number scam with secrecy - a Punjab-specific pattern.",
  "pa", "text", "+917696230418",
  "ਸਤ ਸ੍ਰੀ ਅਕਾਲ ਮਾਮਾ ਜੀ, ਮੈਂ ਕੈਨੇਡਾ ਤੋਂ ਗੁਰਪ੍ਰੀਤ ਬੋਲ ਰਿਹਾ ਹਾਂ, ਇਹ ਮੇਰਾ ਨਵਾਂ ਨੰਬਰ ਹੈ। ਮੇਰਾ ਇੱਕ ਦੋਸਤ ਇੰਡੀਆ ਵਿੱਚ ਹਸਪਤਾਲ ਵਿੱਚ ਦਾਖਲ ਹੈ, ਉਸਨੂੰ ਤੁਰੰਤ ₹1,80,000 ਚਾਹੀਦੇ ਹਨ। ਮੈਂ ਇੱਥੋਂ ਸਿੱਧੇ ਨਹੀਂ ਭੇਜ ਸਕਦਾ, ਤੁਸੀਂ ਹੁਣੇ ਭੇਜ ਦਿਓ, ਮੈਂ ਕੱਲ੍ਹ ਤੁਹਾਡੇ ਖਾਤੇ ਵਿੱਚ ਡਾਲਰ ਭੇਜ ਦਿਆਂਗਾ। ਘਰ ਕਿਸੇ ਨੂੰ ਨਾ ਦੱਸਣਾ, ਮੰਮੀ ਪਰੇਸ਼ਾਨ ਹੋ ਜਾਣਗੇ।"),
S("R-or-T", "govt_scheme",
  "Odia script and Odia numerals; Subhadra-scheme eKYC 'processing fee'.",
  "or", "text", "+919437205816",
  "ସୁଭଦ୍ରା ଯୋଜନା: ଆପଣଙ୍କ ପରବର୍ତ୍ତୀ କିସ୍ତି ₹୫,୦୦୦ ଅଟକି ରହିଛି କାରଣ ଆପଣଙ୍କ ଇ-କେୱାଇସି ଅସମ୍ପୂର୍ଣ୍ଣ। ଟଙ୍କା ପାଇବା ପାଇଁ ଆଜି ହିଁ ₹୧୦୦ ପ୍ରକ୍ରିୟାକରଣ ଶୁଳ୍କ ଦେଇ ଇ-କେୱାଇସି ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ। ଯୋଗାଯୋଗ: ୯୪୩୭୨ ୦୫୮୧୬"),
S("R-ur-T", "pilgrimage_booking",
  "Urdu (right-to-left Arabic script); too-cheap Umrah package with advance and 'ticket on WhatsApp'.",
  "ur", "text", "+917006419253",
  "السلام علیکم! عمرہ پیکج 2026 خصوصی رعایت: صرف ₹65,000 میں 15 دن، ویزا، ٹکٹ اور حرم کے قریب ہوٹل شامل۔ صرف 12 سیٹیں باقی ہیں۔ آج ہی ₹25,000 ایڈوانس جمع کر کے اپنی سیٹ پکی کریں، ٹکٹ واٹس ایپ پر بھیج دیا جائے گا۔ رابطہ: الحرمین ٹورز، 7006419253"),
]

# =====================================================================
# SCAM - CALL DESCRIPTIONS (22 non-regional + 3 regional = 25)
# =====================================================================
items += [
S("C1", "digital_arrest",
  "Long first-person retelling with every classic beat (courier -> cyber crime -> Skype -> 'RBI verification'); checks that the call path catches the full script.",
  "en", "call", None,
  "Yesterday afternoon a man called saying he was from FedEx, Mumbai. He said a parcel booked with my Aadhaar to Taiwan had 5 passports, 3 credit cards and 150 grams of MD drugs. He transferred the call to 'Mumbai Cyber Crime' and an officer in uniform came on Skype video. He showed me an FIR with my photo and said I'm a suspect in money laundering, I can't leave the room or tell my husband. Now he wants me to move my savings to an RBI account for 'verification' and says it will come back in 2 hours with a clearance certificate. He's calling again at 10."),
S("C2", "digital_arrest",
  "Hinglish retelling of the TRAI-IVR -> police hand-off; no money asked yet.",
  "hinglish", "call", None,
  "Subah ek recorded call aaya - 'main TRAI se bol raha hoon, aapka mobile number 2 ghante me band ho jayega, adhik jaankari ke liye 9 dabayein'. 9 dabaya to ek aadmi bola mere Aadhaar pe Mumbai me ek aur SIM li gayi hai jisse logon ko galat message gaye hain, aur Tilak Nagar police station me case hai. Phir usne call 'inspector sahab' ko transfer kar diya jo bole abhi WhatsApp video pe statement dena padega."),
S("C3", "digital_arrest",
  "Hindi retelling with a fake online 'court hearing' and a 'Supreme Court safe account'.",
  "hi", "call", None,
  "एक आदमी का फोन आया, बोला ED (प्रवर्तन निदेशालय) दिल्ली से बोल रहा हूँ। बोला आपके आधार से केनरा बैंक में एक खाता खुला है जिसमें 2 करोड़ का हवाला पैसा आया है, आपके नाम पर अरेस्ट वारंट निकला है। फिर वीडियो कॉल पर एक 'जज साहब' के सामने ऑनलाइन सुनवाई कराई। बोले जमानत के लिए अपनी FD तोड़कर पैसा 'सुप्रीम कोर्ट के सुरक्षित खाते' में डालो, जांच के बाद वापस मिल जाएगा। मैंने अभी तक कुछ नहीं भेजा।"),
S("C5", "voice_clone",
  "Voice-clone emergency; the familiar voice is offered as proof; 'havaldar' settlement + secrecy.",
  "hinglish", "call", None,
  "Raat 11 baje mere bhatije ki awaaz me call aaya, ro raha tha - 'chachu mera accident ho gaya, ek aadmi ko chot lagi hai, police le gayi'. Phir ek aadmi ne phone liya, bola main havaldar hoon, settlement ke liye abhi ₹40,000 GPay karo warna FIR ho jayegi, aur ghar pe kisi ko mat batana. Number unknown tha par awaaz bilkul usi ki thi."),
S("C7", "army_olx_buyer",
  "Seller-side 'scan and enter PIN to receive' with a ₹1 test; army-canteen excuse.",
  "en", "call", None,
  "I listed my old Activa on OLX. A man called saying he's in the Army, posted in Pathankot, and he'll pay my full asking price without seeing it. He said army payments go through their canteen system, so he sent me a QR code on WhatsApp and told me to scan it in GPay and enter my PIN to 'receive' ₹38,000. First he wants me to try with ₹1 to check it works."),
S("C8", "fake_customer_care",
  "Victim initiated the call (number from a search result), so there is no unsolicited contact; the screen-sharing app is the tell.",
  "en", "call", None,
  "My Swiggy refund didn't come, so I searched Google for Swiggy customer care and called the first number. The man was very helpful and said he'd process the refund, but I need to install an app from the link he sent so he can 'see the problem' on my screen, and then open my bank app. He's waiting on the line."),
S("C9", "sim_swap_esim",
  "Instructions sound like a genuine operator process (121, eSIM); 'network will be off, don't worry' is the giveaway.",
  "hinglish", "call", None,
  "Airtel se call aaya ki mera SIM purana ho gaya hai, aaj raat se band ho jayega, 5G ke liye eSIM me upgrade karna padega. Usne bola apne phone se 121 pe SMS bhejo - 'eSIM' aur uske aage ek email ID jo usne batayi. Bola 15 minute me naye eSIM ka QR email pe aa jayega aur network 2-3 ghante band rahega, ghabrana mat."),
S("C10", "call_forwarding",
  "Call-forwarding USSD described in words ('star 4 0 1 star'); nothing about money, OTP or links.",
  "en", "call", None,
  "A courier delivery guy called and said he's near my house with a Blue Dart parcel but the address is incomplete. He said to confirm delivery I just have to dial a code from my phone - star 4 0 1 star and then a number he gave me - and then he'll come. He sounded normal."),
S("C11", "kyc_update",
  "Post-loss Hindi retelling; caller knew name and last 4 digits; OTP described as 'the number in the message'.",
  "hi", "call", None,
  "एक लड़के का फोन आया, बोला SBI के KYC विभाग से बोल रहा हूँ, KYC न होने से आपका खाता आज बंद हो जाएगा। उसने मेरा नाम और खाते के आखिरी 4 नंबर सही बताए। बोला एक मैसेज आएगा, उसमें जो नंबर है वो बता दो, KYC हो जाएगा। मैंने बता दिया, उसके बाद खाते से ₹24,000 कट गए। अब क्या करूँ?"),
S("C12", "credit_card_otp",
  "Polite, knows personal details, offers a benefit (no threat); OTP called a 'confirmation code'.",
  "en", "call", None,
  "A very polite lady from my bank's credit card department called. She knew my name and the last 4 digits of my card. She said I'm eligible for a free limit increase from ₹50,000 to ₹1.5 lakh, and for that she'd send a confirmation code to my phone which I just have to read out to her. She said the offer is only valid today."),
S("C13", "utility_disconnection",
  "Tiny ₹10 payment + app install sent over WhatsApp; Hinglish.",
  "hinglish", "call", None,
  "Bijli office se ek aadmi ka phone aaya, bola aapka pichhle mahine ka bill system me update nahi hua isliye aaj raat 9:30 baje line kaat denge. Usne WhatsApp pe ek link bheja aur bola usme se 'Bill Update' app daal ke bas ₹10 pay kar do, sab theek ho jayega."),
S("C14", "loan_fee",
  "Hindi; an 'RBI-stamped' approval letter offered as proof; upfront file charge + insurance.",
  "hi", "call", None,
  "फाइनेंस कंपनी से एक मैडम का फोन आया, बोलीं आपका ₹3 लाख का पर्सनल लोन बिना CIBIL के पास हो गया है। व्हाट्सएप पर RBI की मुहर वाला अप्रूवल लेटर भी भेजा। बोलीं पैसा खाते में डालने से पहले आज ही ₹3,499 फाइल चार्ज और ₹2,000 इंश्योरेंस भरना होगा।"),
S("C15", "fake_job_fee",
  "'Pre-screened, no interview' selection plus a 'refundable' training/gate-pass fee.",
  "en", "call", None,
  "A lady called saying she's from an airline recruitment agency and I've been selected for an airport ground staff job at Delhi airport, salary ₹32,000. She said there's no interview because my resume was 'pre-screened'. I just need to pay ₹6,500 today for the training kit and gate-pass verification, which will be refunded with my first salary."),
S("C16", "investment_scam",
  "No threat and no fee - just an investment pitch; 'guaranteed IPO allotment' through a private app is the tell.",
  "en", "call", None,
  "After I clicked an Instagram ad about free stock market classes, a woman called saying she's the assistant of a SEBI-registered advisor. She added me to a WhatsApp group where everyone posts big profits every day. Now she says I should install their 'institutional trading' app, because through it we get IPO shares from a special quota with guaranteed allotment. Minimum ₹50,000 to start."),
S("C17", "sextortion",
  "Two-stage: sextortion, then a fake-police 'YouTube delete fee'.",
  "hinglish", "call", None,
  "Raat ko unknown number se ek ladki ka WhatsApp video call aaya, maine utha liya, wo kapde utaar rahi thi, maine turant kaat diya. 10 minute baad usne ek recording bheji jisme mera chehra dikh raha tha aur bola ₹15,000 bhejo warna sabko bhej dungi. Agle din ek aadmi ka call aaya, bola Delhi Police Cyber Cell se, video YouTube pe upload ho gaya hai, delete karwane ki fees lagegi."),
S("C18", "govt_scheme",
  "Short Hindi; a real grievance (missed instalment) makes it believable; OTP not named.",
  "hi", "call", None,
  "किसान सम्मान निधि दफ्तर से फोन आया कि मेरी किस्त ई-केवाईसी की वजह से रुकी हुई है। बोले फोन पर ही ई-केवाईसी कर देंगे, बस आधार नंबर और जो मैसेज में नंबर आए वो बताना है। पिछली किस्त भी नहीं आई थी।"),
S("C19", "govt_scheme",
  "Caller knows leaked pension details (PPO, branch); timed to the life-certificate season; told by a family member.",
  "en", "call", None,
  "My father is 78 and gets a central government pension. A man called him today saying he's from the pension office. He knew Papa's PPO number, retirement date and bank branch. He said this year's life certificate isn't updated and the pension will stop from November, but he can do it on the phone itself - Papa just has to tell him the OTP that comes from UIDAI."),
S("C20", "insurance_bonus",
  "Regulator (IRDAI) impersonation; 'pay GST/TDS first to release your money'; caller knew the policy number.",
  "hinglish", "call", None,
  "Ek sir ka call aaya, bole IRDAI se bol rahe hain. Bole meri purani LIC policy jo 2015 me band ho gayi thi uska bonus ₹3,40,000 pending hai. Paisa release karne ke liye pehle 18% GST aur TDS ka ₹12,600 jama karna hoga, uske baad poora paisa account me aa jayega. Unhone meri policy ka number bhi sahi bataya."),
S("C21", "refund_sent_by_mistake",
  "'Sent by mistake' with a fake credit SMS and a family-friend pretext; Hindi.",
  "hi", "call", None,
  "एक आदमी का फोन आया, बोला मैं आपके पापा का पुराना दोस्त हूँ, उन्हें पैसे भेजने हैं पर उनका नंबर नहीं लग रहा, आपके खाते में भेज देता हूँ। फिर ₹20,000 जमा होने का SMS आया। थोड़ी देर बाद फिर फोन किया कि गलती से 2,000 की जगह 20,000 चले गए, बाकी ₹18,000 वापस कर दो, बहुत ज़रूरी है। पर मेरे बैंक ऐप में बैलेंस नहीं बढ़ा।"),
S("C22", "rent_property_advance",
  "Rent advance without viewing; 'Navy officer' identity with an Aadhaar copy as 'proof'.",
  "en", "call", None,
  "I found a flat on a Facebook group. The owner says he's a Navy officer posted in Vizag so he can't show it, and the guard doesn't have keys. He sent photos and his Aadhaar copy and asked me to pay two months' rent plus deposit, ₹45,000, by UPI today. He'll courier the keys and agreement after payment. He said many people are interested."),
S("C23", "voter_sir_otp",
  "Emerging 2025-26 SIR/BLO pretext; 'code' instead of OTP; no money mentioned.",
  "hi", "call", None,
  "एक आदमी का फोन आया, बोला मैं BLO बोल रहा हूँ, SIR में आपका नाम वोटर लिस्ट में 'डुप्लीकेट' दिख रहा है, कल तक ठीक नहीं हुआ तो नाम कट जाएगा। बोला अभी आपके फोन पर एक कोड आएगा, बस वो बता दीजिए, मैं ऑनलाइन ठीक कर दूँगा। घर पर कोई नहीं आया।"),
S("C24", "lottery_kbc",
  "Victim is excited, not worried; a physical scratch-card letter makes it feel real.",
  "en", "call", None,
  "I got a letter by post from 'Naaptol' with a scratch card. I scratched it and won a Tata Nexon car or ₹12.8 lakh cash! I called the number on the card and the man said congratulations, but first I must pay a 1% registration fee of ₹12,800, then the cash comes in 3 days. He even sent me a winner certificate with a stamp."),
# regional calls
S("R-ta-C", "digital_arrest",
  "Tamil retelling of courier -> 'Mumbai police' video call; never uses the words 'digital arrest' (only 'don't switch off the camera, tell no one').",
  "ta", "call", None,
  "நேற்று மதியம் ஒருவர் போன் செய்து, FedEx மும்பை அலுவலகத்திலிருந்து பேசுவதாகச் சொன்னார். என் ஆதார் எண்ணில் தைவானுக்கு அனுப்பப்பட்ட பார்சலில் போதைப்பொருளும் 5 போலி பாஸ்போர்ட்டுகளும் இருப்பதாகச் சொன்னார். பிறகு மும்பை போலீஸ் அதிகாரி என்று ஒருவர் சீருடையில் வீடியோ காலில் வந்தார். விசாரணை முடியும் வரை கேமராவை அணைக்கக்கூடாது, வீட்டில் யாரிடமும் சொல்லக்கூடாது என்றார். என் FD பணத்தை சரிபார்ப்புக்காக அவர்கள் சொல்லும் கணக்குக்கு அனுப்ப வேண்டுமாம், பிறகு திருப்பித் தருவார்களாம். இது உண்மையா?"),
S("R-te-C", "relative_emergency",
  "Telugu retelling of a fake-police video call about a son 'caught'; a crying voice in the background; money for 'no case'.",
  "te", "call", None,
  "ఈ రోజు ఉదయం ఒక తెలియని నంబర్ నుంచి వీడియో కాల్ వచ్చింది, ప్రొఫైల్ ఫోటోలో పోలీస్ లోగో ఉంది. పోలీస్ యూనిఫాంలో ఉన్న వ్యక్తి 'మీ అబ్బాయి ఒక అమ్మాయిని వేధించిన కేసులో పట్టుబడ్డాడు, కేసు పెట్టకుండా వదిలేయాలంటే వెంటనే ₹50,000 పంపండి' అన్నాడు. వెనకాల ఒక అబ్బాయి ఏడుస్తూ 'అమ్మా, కాపాడు' అని అరిచాడు. మా అబ్బాయి కాలేజీలో ఉన్నాడు, ఫోన్ ఎత్తడం లేదు."),
S("R-bn-C", "govt_scheme",
  "Bengali retelling; 'block office' caller about Lakshmir Bhandar; OTP described as 'the six-digit number'.",
  "bn", "call", None,
  "আজ দুপুরে একটা ফোন এল, বলল ব্লক অফিস থেকে বলছে। বলল আধার লিঙ্ক না থাকায় আমার লক্ষ্মীর ভাণ্ডারের টাকা বন্ধ হয়ে যাবে, এখনই ফোনেই ঠিক করে দেবে। একটা মেসেজ আসবে, তাতে যে ছয় অঙ্কের নম্বর থাকবে সেটা বলে দিতে বলল। আমি এখনও বলিনি।"),
]

# =====================================================================
# GENUINE - TEXT (non-regional, 47)
# =====================================================================
items += [
G("g01", "bank_otp",
  "Real card-OTP template: contains 'OTP', an amount, card digits and 'do not share'.",
  "en", "text", "AD-HDFCBK-T",
  "OTP is 482913 for txn of INR 2,499.00 at AMAZON PAY INDIA on HDFC Bank card ending 4417. Valid till 14:32. Do not share OTP for security reasons."),
G("g02", "bank_otp",
  "Login OTP plus a 'never asks for OTP/PIN/password' warning - dense with scam vocabulary.",
  "en", "text", "VM-SBIINB-T",
  "Your OTP for login to OnlineSBI is 719204, valid for 3 minutes. SBI never asks for your OTP, PIN or password over call, SMS or email. Do not share it with anyone. -SBI"),
G("g03", "bank_otp",
  "Hindi OTP for UPI-PIN setup: 'UPI पिन', 'OTP' and 'साझा' all appear.",
  "hi", "text", "JD-PNBSMS-T",
  "प्रिय ग्राहक, UPI पिन सेट करने के लिए आपका OTP 308145 है, जो 5 मिनट के लिए मान्य है। इसे किसी के साथ साझा न करें। बैंक कभी भी OTP या पिन नहीं मांगता। -पीएनबी"),
G("g05", "aadhaar_otp",
  "Real UIDAI OTP template that itself says 'update Aadhaar', 'upload documents' and 'call'. A scam copy (forward-to-cancel) is in this set.",
  "en", "text", "VK-UIDAI-G",
  "OTP for Aadhaar (XX7712) is 845210 (valid for 10 mins). To update Aadhaar, upload documents on myAadhaar.uidai.gov.in or visit Aadhaar Center. Call 1947 for info. -UIDAI"),
G("g07", "debit_alert",
  "Genuine UPI debit alert with 'Not You? Call' and a 10-digit SMS-block number.",
  "en", "text", "JM-HDFCBK-T",
  "Sent Rs.640.00\nFrom HDFC Bank A/C *4417\nTo ANNAPURNA SWEETS\nOn 06/10/26\nRef 627914258803\nNot You?\nCall 18002586161/SMS BLOCK UPI to 7304412958"),
G("g08", "debit_alert",
  "Terse real SBI format with 'If not u? call'.",
  "en", "text", "AX-SBIUPI-T",
  "Dear UPI user A/C X7731 debited by 250.0 on date 06Oct26 trf to RAMESH KIRANA Refno 627911834552. If not u? call 1800111109. -SBI"),
G("g09", "credit_alert",
  "Salary credit with dispute/BLOCK instructions and a 10-digit number.",
  "en", "text", "VM-ICICIT-T",
  "ICICI Bank Acct XX902 credited with Rs 32,450.00 on 01-Oct-26; NEFT-SUNRISE AUTO COMPONENTS PVT LTD-SALARY SEP. Avl Bal Rs 36,118.20. To report a dispute, call 18002662 or SMS BLOCK 902 to 9206314587."),
G("g10", "credit_alert",
  "'Received money from a UPI ID' - superficially like 'you received money' bait, but nothing is asked.",
  "en", "text", "BZ-KOTAKB-T",
  "Received Rs.450.00 in your Kotak Bank A/c X3381 from priya.n@sahayakdemo on 06-10-26. UPI Ref: 627915550231."),
G("g11", "card_spend_alert",
  "Large spend + 'if not done by you, call' - the template that fake debit alerts copy; toll-free and short code only.",
  "en", "text", "VM-SBICRD-T",
  "Rs.38,990.00 spent on your SBI Credit Card ending 5512 at CROMA RETAIL on 05/10/26. Avl Lmt: Rs.61,010. If not done by you, call 18001801290 or SMS BLOCK 5512 to 5676791. -SBI Card"),
G("g13", "security_alert",
  "'Not done by you? call immediately' urgency, but toll-free numbers and no link.",
  "en", "text", "AD-SBIINB-T",
  "Your OnlineSBI password was changed on 06-Oct-26 at 21:14. If this was not done by you, call our 24x7 helpline 1800 1234 / 1800 2100 immediately. -SBI"),
G("g15", "govt_scheme_credit",
  "Hindi PM-KISAN credit - same scheme name, amount and 'Aadhaar' words as the PM-KISAN scams.",
  "hi", "text", "VM-PMKISN-G",
  "प्रिय लाभार्थी, पीएम-किसान योजना के अंतर्गत ₹2,000 की किस्त आपके आधार से जुड़े बैंक खाते में भेज दी गई है। स्थिति जानने के लिए pmkisan.gov.in देखें। -पीएम-किसान, भारत सरकार"),
G("g16", "pension_credit",
  "Mentions life certificate, Jeevan Pramaan and deadlines - exactly the pension-scam vocabulary.",
  "en", "text", "VM-SBIPSN-T",
  "Your pension for Sep-2026, Rs 18,432.00, has been credited to SB A/c XX5678 on 01-10-2026. Pensioners aged 80+ can submit their Life Certificate from 1 Oct, others in November, at any SBI branch or through Jeevan Pramaan. -SBI CPPC"),
G("g17", "dbt_subsidy_credit",
  "Short DBT credit naming LPG subsidy.",
  "en", "text", "JD-PNBSMS-T",
  "Rs. 300.00 credited to your A/c XX1290 on 05-10-26 towards LPG subsidy (DBTL) for consumer no. 7712045. -PNB"),
G("g18", "scholarship_credit",
  "Scholarship credit with the same amount the scholarship scam uses; official domain.",
  "en", "text", "VK-NSPGOV-G",
  "Dear Student, your scholarship of Rs 12,000 under the Post-Matric Scholarship Scheme for 2025-26 has been credited to your bank account through PFMS. Check status on scholarships.gov.in. -NSP"),
G("g20", "awareness",
  "Awareness text packed with APK / KYC / Aadhaar / reward points / link keywords.",
  "en", "text", "AD-SBIBNK-S",
  "SBI never sends APK files or links on WhatsApp/SMS to update KYC, Aadhaar or reward points. Do not install apps from unknown links. Report fraud at 1930 or cybercrime.gov.in. -SBI"),
G("g21", "awareness",
  "Names CBI/ED/Customs, 'arrest', 'video call' and 'money' - a keyword matcher will fire.",
  "en", "text", "VK-CYBDST-G",
  "There is no such thing as 'digital arrest'. Police, CBI, ED, Customs or courts never arrest anyone or ask for money on a video call. If you get such a call, disconnect and dial 1930 or report at cybercrime.gov.in. - I4C, MHA"),
G("g22", "awareness",
  "Hindi warning containing 'QR', 'scan', 'receive money' and 'UPI PIN'.",
  "hi", "text", "VK-CYBDST-G",
  "सावधान! अगर कोई अनजान व्यक्ति QR कोड भेजकर कहे कि इसे स्कैन करके पैसे प्राप्त करें, तो यह धोखाधड़ी है। पैसे प्राप्त करने के लिए कभी भी UPI पिन की ज़रूरत नहीं होती। शिकायत करें: 1930 - साइबर दोस्त"),
G("g23", "awareness",
  "Mentions USSD forwarding codes, eSIM SMS and a 'KYC' app - the same strings as call-forwarding/eSIM scams.",
  "en", "text", "JX-JIOINF-S",
  "Jio Alert: Beware of callers asking you to dial codes like *401* or *21*, send an 'eSIM' SMS, or install an app for 'KYC'. Jio never asks for these. Report suspected fraud on Sanchar Saathi (sancharsaathi.gov.in) - Chakshu. -Jio"),
G("g24", "awareness",
  "Hinglish awareness listing OTP, PIN, CVV, lottery, KYC and link.",
  "hinglish", "text", "VM-RBISAY-G",
  "RBI Kehta Hai: Apna OTP, PIN, CVV ya password kabhi kisi ko na batayein - bank ya RBI kabhi nahi maangte. Inaam, lottery ya KYC ke naam pe aaye link par click na karein. Shikayat: 1930 / cybercrime.gov.in"),
G("g25", "awareness",
  "Hindi Election Commission advisory on the same SIR / BLO / OTP topic the scams use.",
  "hi", "text", "VK-ECISVP-G",
  "निर्वाचन आयोग: SIR के दौरान BLO आपके घर पहले से भरा हुआ गणना प्रपत्र लेकर आएंगे। कोई भी BLO OTP, बैंक विवरण या शुल्क नहीं मांगेगा। किसी को OTP न बताएं। वोटर हेल्पलाइन: 1950"),
G("g26", "delivery_otp",
  "Instructs the user to share an OTP (with the delivery agent) and contains a short link (Flipkart's own shortener).",
  "en", "text", "JD-FLPKRT-S",
  "Your Flipkart order OD4339127845 is out for delivery today. Share OTP 7713 with the delivery agent only at the time of delivery. Flipkart never asks for OTP over a call. Track: fkrt.it/Lm3QxN"),
G("g27", "lpg_delivery_code",
  "Says 'share this code with the delivery person' - the opposite of the usual rule - and is about gas booking (a 2026 scam theme).",
  "en", "text", "VM-INDANE-S",
  "Dear Customer, your Indane refill booking no. 260944 dated 05-10-26 is confirmed. Delivery Authentication Code (DAC): 4821. Please share the DAC with the delivery person only at the time of cylinder delivery. Cash memo amount Rs 853.00. -IndianOil"),
G("g28", "delivery_otp",
  "Hinglish; tells you to share an OTP and to pay by scanning a QR.",
  "hinglish", "text", "VM-DLHVRY-S",
  "Delhivery: Aapka COD order (Rs 1,149) aaj deliver hoga. Delivery boy ko OTP 3901 tabhi batayein jab parcel aapke haath me ho. Payment cash ya delivery boy ke device par dikhaye gaye UPI QR se karein."),
G("g29", "utility_bill",
  "Electricity bill with due date, 'pay online' and an official link, but no threat and no phone number.",
  "en", "text", "VM-MSEDCL-S",
  "Dear Consumer, your electricity bill for Sep-26 for Cons. No. 170012345678 is Rs 1,284.00, due on 18-10-26. Pay online at https://wss.mahadiscom.in or the Mahavitaran app, or at any MSEDCL collection centre. Ignore if already paid. -MSEDCL"),
G("g30", "utility_bill",
  "Genuinely says 'unpaid' and 'to avoid disconnection' - the core words of the electricity scam - but points only to official channels.",
  "en", "text", "VM-BESCOM-S",
  "BESCOM: Your electricity bill of Rs 2,140 for Account ID 7521098345 was due on 25-09-26 and is unpaid. Please pay by 10-10-26 to avoid disconnection as per KERC regulations. Pay via BESCOM Mithra app, Bangalore One centres or any BESCOM cash counter. Ignore if paid."),
G("g31", "utility_bill",
  "Piped-gas bill with 'BP No.' and a late-charge warning (same props as gas-disconnection scams).",
  "en", "text", "VM-MGLBIL-S",
  "MGL: Your gas bill of Rs 612.40 for BP No. 1100234567 is generated, due date 20-10-2026. Pay via MGL Connect app or the official website. Late payment charges apply after the due date. -Mahanagar Gas"),
G("g33", "csc_camp",
  "Mentions Ayushman / Vay Vandana cards and a personal 10-digit number, but asks for no money.",
  "hi", "text", "+919451207386",
  "ग्राम पंचायत रामपुर: शनिवार 10 अक्टूबर को पंचायत भवन में आयुष्मान कार्ड, ई-श्रम कार्ड और वय वंदना कार्ड बनाने का कैंप सुबह 10 से 4 बजे तक लगेगा। आधार कार्ड, राशन कार्ड और मोबाइल साथ लाएं। कार्ड बनवाना बिल्कुल मुफ्त है। संपर्क: VLE सुरेश यादव 9451207386"),
G("g34", "aadhaar_camp",
  "Legitimately states fees for Aadhaar updates - a real fee in a government-sounding message.",
  "en", "text", "AD-INDPST-G",
  "India Post: Special Aadhaar enrolment & update camp at Head Post Office, Civil Lines on 12-13 Oct, 9 AM-4 PM. New enrolment and mandatory biometric update for children are free; demographic update Rs 75, biometric update Rs 125 as per UIDAI. Carry original documents."),
G("g35", "relative_money_request",
  "Family money request - same shape as the 'new number' scam but known account, no urgency, no secrecy.",
  "hinglish", "text", "+919876023415",
  "Bhaiya, college fees ki last date 10 tarikh hai, ₹4,500 bhej doge? Wahi purane account me jo papa use karte hain. Koi jaldi nahi, kal tak chalega. Ghar pe sab theek?"),
G("g36", "relative_money_request",
  "Hindi money request from a child to a parent; usual account, no urgency.",
  "hi", "text", "+918698042317",
  "माँ, मकान मालिक को 5 तारीख तक किराया देना है, ₹6,000 मेरे SBI वाले खाते में डाल देना जब टाइम मिले। रात को ऑफिस के बाद फोन करता हूँ।"),
G("g37", "shop_promotion",
  "'Lucky draw', 'bumper inaam', 'FREE', Diwali - all scam words - but the draw is in-store, no fee or link.",
  "hinglish", "text", "VM-GUPTAG-P",
  "Gupta Garments, Sadar Bazar 🪔 Diwali Dhamaka! ₹2,000 ki kharidari par lucky draw coupon FREE. Bumper inaam: Scooty, LED TV, mixer. Draw 6 Nov ko dukaan par sabke saamne. Zaroor padhaarein! T&C. Msg band karne ke liye STOP likhein."),
G("g38", "shop_promotion",
  "WhatsApp shop message with a UPI ID and 'free' delivery.",
  "en", "text", "+919822014736",
  "Sharma Kirana Store: Fresh stock of Diwali dry fruits and sweets has arrived. Order on WhatsApp, free home delivery above ₹500. Pay on delivery by cash or UPI to sharmakirana@sahayakdemo. Thank you for shopping with us!"),
G("g39", "shop_promotion",
  "Real-style promo with urgency ('hurry', 'ends at midnight', '80% off') and an unknown-but-benign link; nothing to pay or install.",
  "en", "text", "VK-STYLKT-P",
  "Big Festive Sale is LIVE! Up to 80% off on fashion + extra 10% instant discount on select bank cards. Hurry, today's deals end at midnight. Shop now: stylekart.in/festive  T&C apply."),
G("g40", "job_interview",
  "Shortlisting + the word 'fee' + a mobile number; genuine because nothing is asked for.",
  "en", "text", "+919310457286",
  "Dear Anjali, you have been shortlisted for the Customer Support Associate (Hindi/English) role at Orbit BPO Services. Walk-in interview: Fri 9 Oct 2026, 11 AM, Tower B, Sector 62, Noida. Please carry your resume, an Aadhaar copy and one photo. We do not charge any fee at any stage of hiring. For queries call HR Neha on 9310457286."),
G("g41", "job_interview",
  "Informal Hinglish job call-up from a mobile number.",
  "hinglish", "text", "+918007213649",
  "Hi Rahul, Swastik Motors se Pooja bol rahi hoon. Aapne mechanic helper post ke liye apply kiya tha. Kal subah 11 baje workshop pe aa jaana - Bhosari MIDC, plot 41. Original certificates saath laana. Salary ₹14,000 + overtime."),
G("g42", "insurance_renewal",
  "Policy number + due + pay; LIC is also a common scam brand.",
  "en", "text", "VM-LICIND-S",
  "LIC: Premium of Rs 6,542.00 for Policy No. 451837209 is due on 15-Oct-2026 (grace period till 14-Nov-2026). Pay via LIC customer portal, LIC Digital app, licindia.in or at any LIC branch. Ignore if already paid."),
G("g43", "insurance_renewal",
  "Expiry + 'renew' + a personal agent mobile number.",
  "en", "text", "AD-BHSGIC-S",
  "Your two-wheeler insurance for MH12 RT 4471 expires on 20-Oct-2026. Renew before expiry to keep your No Claim Bonus. Renew in our app or contact your advisor Ramesh Patil (9822031476). Ignore if already renewed. -Bharat Suraksha General Insurance"),
G("g44", "echallan_official",
  "Real e-challan template on the official domain - scams copy this text nearly word for word.",
  "en", "text", "VK-DLTRFC-G",
  "Challan No. DL1234567891011 issued on 04/10/2026 for vehicle DL3CAB1234, violation: parking in No Parking zone. Fine Rs 500. Pay online at https://echallan.parivahan.gov.in or at the traffic court. -Delhi Traffic Police"),
G("g45", "itr_refund_official",
  "Tax refund + bank account + portal link - the same words as the refund scam.",
  "en", "text", "AD-ITDCPC-G",
  "Your ITR for AY 2026-27 (PAN XXXXX1234X) has been processed at CPC. A refund of Rs 4,520 has been determined and sent to your pre-validated bank account. For details, log in to the e-Filing portal www.incometax.gov.in. -ITD"),
G("g46", "bank_kyc_reminder",
  "Real periodic re-KYC reminder: 'KYC due', 'update', 'RBI guidelines'.",
  "en", "text", "AD-BOBSMS-S",
  "Dear Customer, KYC for your A/c XX4471 is due for periodic updation as per RBI guidelines. Please submit a self-declaration at your home branch or through bob World app / Internet Banking. The Bank never asks for KYC details through calls, SMS links or email. -Bank of Baroda"),
G("g47", "sim_change_notice",
  "Genuine SIM-swap notification - the very event the eSIM scam exploits.",
  "en", "text", "VM-AIRTEL-S",
  "Your request for a SIM change on mobile number 98XXXXX412 has been received at Airtel Store, Karol Bagh at 11:42. SMS and calls will be paused for 24 hours for your security. If you did not request this, call 121 immediately. -Airtel"),
G("g48", "merchant_refund",
  "Refund wording with no ask.",
  "en", "text", "JD-AMAZON-S",
  "Refund of Rs 1,299.00 for your return of order 408-2215034-6617209 has been initiated to your original payment method (UPI). It will reflect in 3-5 business days. No action is needed from you. -Amazon"),
G("g50", "preapproved_loan_offer",
  "'Pre-approved', 'instant', 'no paperwork' - loan-scam vocabulary in a real bank promotion that points only to its own app.",
  "en", "text", "VM-SBIINB-P",
  "SBI: A pre-approved personal loan of up to Rs 2,00,000 is available for you in the YONO SBI app. Instant disbursal, no paperwork, zero processing fee till 31 Oct. Apply only through the YONO SBI app. T&C apply."),
G("g51", "ipo_allotment",
  "'IPO' and 'allotted' - the investment-scam hook words - in an exchange notification.",
  "en", "text", "AD-NSEIPO-S",
  "Dear Investor, you have been allotted 1 lot (18 shares) in the ABC Technologies Ltd IPO. Shares will be credited to your demat account by 09-Oct-2026; listing on 10-Oct-2026. -NSE"),
G("g52", "olx_buyer_genuine",
  "OLX buyer from an unknown number - but wants to inspect in person and pays on the spot.",
  "en", "text", "+918007312946",
  "Hi, I saw your Hero cycle on OLX for ₹4,500. Is it still available? I can come to see it on Sunday morning near Kothrud. If it's in good condition I'll pay cash or UPI on the spot."),
G("g53", "rent_listing_genuine",
  "Rent, deposit and 'token' words, but the visit comes first.",
  "en", "text", "+919765203187",
  "Hello, this is Mrs. Kulkarni about the 1BHK in Baner. Rent ₹15,000, deposit two months. You can see the flat on Saturday at 11 am - my son will show it. Token only after you see it and we sign the agreement."),
G("g55", "customer_care_reply",
  "Complaint + refund + 'OTP / UPI PIN' words; no ask.",
  "en", "text", "JD-ZOMATO-S",
  "We've received your complaint #ZM8812345 about a missing item. A refund of ₹180 has been processed to your Zomato wallet. For further help, use 'Help' in the app. Zomato never asks for your OTP or UPI PIN."),
]

# =====================================================================
# GENUINE - CALLS (8)
# =====================================================================
items += [
G("GC1", "delivery_otp",
  "Victim reports sharing an OTP on request - normally the strongest scam signal - but in the correct doorstep-delivery context.",
  "en", "call", None,
  "The Flipkart delivery boy called to say he was at my gate. I went down, he handed me the parcel and then asked me to tell him the 4-digit OTP that came by SMS so he could mark it delivered. I told him and he left. Was that okay?"),
G("GC2", "bank_fraud_check_call",
  "Bank calling about a transaction - the pretext of many scams - with nothing requested.",
  "en", "call", None,
  "Got a call from a number showing 'HDFC Bank'. A lady asked if I had made a ₹38,990 purchase at Croma yesterday. I said yes, it was my TV. She said thank you, the card is fine, and if I ever see a transaction I didn't do I should call the number on the back of my card. She didn't ask for any OTP, PIN or card number."),
G("GC3", "job_interview",
  "Job call that mentions fees only to say there are none.",
  "hinglish", "call", None,
  "Ek ladki ka call aaya Orbit BPO se, boli maine Naukri pe jo apply kiya tha uske liye interview hai Thursday ko 11 baje, Sector 62 wale office me. Resume aur Aadhaar ki copy laani hai. Maine poocha koi fees lagegi? Boli koi fees nahi hai, details email pe bhi aa jayengi."),
G("GC4", "relative_money_request",
  "Relative asks for money on a call; known number, no urgency or secrecy.",
  "en", "call", None,
  "My brother called from his usual number this morning. His salary is late this month and he asked if I could lend him ₹5,000 for his son's school trip; he'll return it on the 1st. He said there's no hurry, I can send it to his account in the evening."),
G("GC5", "csc_camp",
  "Hindi call about Ayushman cards (a common fee-scam theme) with no ask.",
  "hi", "call", None,
  "आशा दीदी का फोन आया था, बोलीं शनिवार को पंचायत भवन में आयुष्मान कार्ड बनाने का कैंप है, आधार कार्ड और राशन कार्ड लेकर आना, कोई पैसा नहीं लगेगा।"),
G("GC6", "lpg_delivery_code",
  "Asks to tell an SMS code to the delivery man - the genuine LPG DAC process.",
  "hinglish", "call", None,
  "Gas agency se call aaya ki kal cylinder aayega, ₹853 ready rakhna, aur jab cylinder mil jaye tab delivery wale ko SMS wala DAC code bata dena."),
G("GC7", "police_verification_call",
  "A police call - the trigger for digital-arrest scams - that is routine passport verification (come to the station, no money).",
  "en", "call", None,
  "A constable from our local police station called about my passport verification. He asked me to come to the station tomorrow between 10 and 1 with my Aadhaar, address proof and the names of two neighbours. He didn't ask for any money and gave me the station's landline number to confirm."),
G("GC8", "power_cut_notice",
  "Electricity-department call about a power cut; no ask.",
  "hinglish", "call", None,
  "Bijli office se lineman ka phone aaya ki kal subah 10 se 2 baje tak hamare area me maintenance ke liye light nahi rahegi. Bas batane ke liye call kiya tha, kuch maanga nahi."),
]

# =====================================================================
# GENUINE - REGIONAL TEXT (5)
# =====================================================================
items += [
G("GR1-mr", "govt_scheme_credit",
  "Same scheme and instalment as the Marathi eKYC scam, Marathi numerals; genuine credit notice that also warns against paying.",
  "mr", "text", "VM-MAHGOV-G",
  "महाराष्ट्र शासन: मुख्यमंत्री माझी लाडकी बहीण योजनेअंतर्गत ऑक्टोबर महिन्याचा ₹१,५०० चा हप्ता आपल्या आधार संलग्न बँक खात्यात जमा करण्यात आला आहे. या योजनेसाठी कोणतेही शुल्क आकारले जात नाही; कोणालाही OTP किंवा पैसे देऊ नका."),
G("GR2-bn", "govt_scheme_credit",
  "Bengali scheme-credit notice; mentions OTP and money inside a warning.",
  "bn", "text", "VM-WBGOVT-G",
  "পশ্চিমবঙ্গ সরকার: লক্ষ্মীর ভাণ্ডার প্রকল্পের অক্টোবর মাসের ₹১,০০০ আপনার আধার-যুক্ত ব্যাংক অ্যাকাউন্টে জমা হয়েছে। এই প্রকল্পের জন্য কেউ টাকা বা OTP চাইলে দেবেন না।"),
G("GR3-ta", "awareness",
  "Tamil police advisory naming digital arrest, CBI, customs, video call and money.",
  "ta", "text", "VK-TNPCYB-G",
  "தமிழ்நாடு காவல்துறை சைபர் குற்றப் பிரிவு: 'டிஜிட்டல் கைது' என்று எதுவும் இல்லை. காவல்துறை, CBI அல்லது சுங்கத் துறை யாரையும் வீடியோ அழைப்பில் கைது செய்யாது, பணமும் கேட்காது. இப்படிப்பட்ட அழைப்பு வந்தால் உடனே துண்டித்து 1930-க்கு அழைக்கவும்."),
G("GR4-te", "utility_bill",
  "Telugu electricity bill with due date and surcharge; no threat or number.",
  "te", "text", "VM-TGSPDC-S",
  "TGSPDCL: మీ సర్వీస్ నెం. 1104235678 కు సెప్టెంబర్ నెల విద్యుత్ బిల్లు ₹642. చెల్లింపు గడువు 15-10-2026. గడువు దాటితే సర్‌చార్జీ వర్తిస్తుంది. TGSPDCL యాప్ లేదా కౌంటర్ ద్వారా చెల్లించండి. ఇప్పటికే చెల్లించి ఉంటే దయచేసి పట్టించుకోకండి."),
G("GR5-gu", "shop_promotion",
  "Gujarati Navratri offer with 'lucky draw' and 'free' - in-store only.",
  "gu", "text", "+919824107356",
  "શ્રી ખોડિયાર ડ્રેસીસ, મણિનગર 🪔 નવરાત્રી ઓફર! ચણિયા ચોળી પર 30% સુધી છૂટ. ₹3,000ની ખરીદી પર લકી ડ્રો કૂપન મફત. ઓફર 20 ઓક્ટોબર સુધી. દુકાને જરૂર પધારો!"),
]

# =====================================================================
# UPI QR PAYLOADS (8 scam + 4 genuine)
# =====================================================================
q = urllib.parse.quote
hindi_tn = q("ई-केवाईसी शुल्क - किस्त जारी करने हेतु", safe="")
items += [
S("Q1", "qr_receive_cashback",
  "A pay request whose note says 'Scan to receive cashback'; brand-like payee name.",
  "en", "qr", None,
  "upi://pay?pa=cashback.desk@sahayakdemo&pn=PhonePe%20Cashback%20Desk&am=1999.00&cu=INR&tn=Scan%20to%20receive%20Rs%201999%20cashback"),
S("Q2", "qr_refund",
  "'Enter PIN to credit' refund wording on a pay request; e-commerce brand as payee.",
  "en", "qr", None,
  "upi://pay?pa=refund.center@sahayakdemo&pn=Flipkart%20Refund%20Center&am=4999&cu=INR&tn=Refund%20approval%20-%20enter%20PIN%20to%20credit%20amount"),
S("Q3", "qr_prize_fee",
  "'+' used for spaces (decoder must handle it); prize 'GST and processing fee'.",
  "en", "qr", None,
  "upi://pay?pa=kbc.prize.office@sahayakdemo&pn=KBC+Prize+Office&am=12500&cu=INR&tn=GST+and+processing+fee+for+Rs+25+lakh+prize"),
S("Q4", "qr_official_fee",
  "Government department as payee collecting a 'reactivation' fee; no 'receive' wording.",
  "en", "qr", None,
  "upi://pay?pa=dot.reactivation@sahayakdemo&pn=Department%20of%20Telecommunications&am=2500&cu=INR&tn=SIM%20reactivation%20and%20KYC%20verification%20charge"),
S("Q5", "qr_safe_account",
  "Digital-arrest 'RBI safe account' as a QR; large amount labelled 'refundable'.",
  "en", "qr", None,
  "upi://pay?pa=rbi.verification@sahayakdemo&pn=RBI%20Fund%20Verification%20Cell&am=95000&cu=INR&tn=Temporary%20deposit%20-%20refundable%20after%20verification"),
S("Q6", "qr_scheme_fee",
  "Hindi note percent-encoded as UTF-8 (must be decoded to read); official scheme name collecting an eKYC fee.",
  "hi", "qr", None,
  f"upi://pay?pa=pmkisan.ekyc@sahayakdemo&pn=PM%20Kisan%20Samman%20Nidhi&am=199&cu=INR&tn={hindi_tn}"),
S("Q7", "qr_army_buyer",
  "₹1 'test' payment from an 'Army canteen' payee whose note promises money back.",
  "en", "qr", None,
  "upi://pay?pa=capt.vikram.army@sahayakdemo&pn=Indian%20Army%20Canteen%20Payment&am=1&cu=INR&tn=Rs%201%20test%20-%20you%20will%20receive%20Rs%202%20back%20then%20full%20Rs%2038000"),
S("Q8", "qr_scheme_fee",
  "Looks like an ordinary merchant bill (merchant code, decimal amount, plain note); only the official-scheme payee name plus a fee for a free card gives it away.",
  "en", "qr", None,
  "upi://pay?pa=pmjay.cardseva@sahayakdemo&pn=Ayushman%20Bharat%20PMJAY%20Card%20Seva&am=350.00&cu=INR&mc=9399&tn=Card%20printing%20charge"),
G("Q9", "qr_shop",
  "Static shop QR with no amount and raw (unencoded) spaces.",
  "en", "qr", None,
  "upi://pay?pa=sharmakirana@sahayakdemo&pn=Sharma Kirana Store&mc=5411&cu=INR"),
G("Q10", "qr_shop",
  "Dynamic bill QR with 'Diwali' and an amount - like festive scams - but a normal sweet-shop bill.",
  "en", "qr", None,
  "upi://pay?pa=annapurnasweets@sahayakdemo&pn=Annapurna%20Sweets&am=640.00&cu=INR&mc=5441&tr=AS2231&tn=Bill%20No%202231%20Diwali%20mithai%20box"),
G("Q11", "qr_shop",
  "Government-branded name ('PM ... Janaushadhi Kendra') on a genuine pharmacy bill.",
  "en", "qr", None,
  "upi://pay?pa=janaushadhi.sec12@sahayakdemo&pn=PM%20Bhartiya%20Janaushadhi%20Kendra%20Sec%2012&am=186.50&cu=INR&mc=5912&tn=Medicines%20bill%20447"),
G("Q12", "qr_friend_split",
  "Person-to-person request from a friend for a shared bill.",
  "en", "qr", None,
  "upi://pay?pa=rahul.verma@sahayakdemo&pn=Rahul%20Verma&am=450&cu=INR&tn=Dinner%20split%20Saturday"),
]

# ---------------------------------------------------------------------
keys = [it["key"] for it in items]
assert len(keys) == len(set(keys)), "duplicate internal keys"

rng = random.Random(20261007)
rng.shuffle(items)
keymap = {}
with OUT.open("w", encoding="utf-8") as fh:
    for n, it in enumerate(items, 1):
        rid = f"rt1-{n:03d}"
        keymap[it["key"]] = rid
        rec = {"id": rid, "label": it["label"], "category": it["category"],
               "technique": it["technique"], "lang": it["lang"],
               "input_type": it["input_type"], "sender": it["sender"],
               "text": it["text"]}
        fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
print(json.dumps(keymap))
print(f"wrote {len(items)} items to {OUT}")
